### ISSUE TITLE
webdriver-manager status w/o any selenium dir throws error

### ISSUE THREAD

**Issue by juliemr** [angular/webdriver-manager#11]
Would be nice if it output a nicer message.

**Comment by cnishina** [comment]
```
node bin/webdriver-manager status
webdriver-manager: using project version 0.1.0
fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/opt/webdriver-manager/selenium'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Function.FileManager.getExistngFiles (/opt/webdriver-manager/built/lib/files/file_manager.js:69:68)
    at Function.FileManager.downloadedBinaries (/optwebdriver-manager/built/lib/files/file_manager.js:114:41)
    at Program.status [as runMethod] (/opt/webdriver-manager/built/lib/cmds/status.js:38:50)
    at Program.run (/opt/webdriver-manager/built/lib/cli/programs.js:60:14)
    at Object.<anonymous> (/opt/webdriver-manager/built/lib/webdriver.js:26:38)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```
