### ISSUE TITLE
Executing with the wrong chrome driver

### ISSUE THREAD

**Issue by DarkArc** [angular/webdriver-manager#118]
We're currently experiencing an issue where our MacOS devs are unable to run protractor. This seems related to #93, however, to the best our knowledge we have successfully updated to the chrome driver version 2.24.

The issue seems to be that the previous 2.22 driver is being used.

The following commands were used in an attempt to verify the system state:

```
YYY% webdriver-manager clean
webdriver-manager: using local installed version 10.2.5
[16:19:59] I/file_manager - removed chromedriver_2.24
[16:19:59] I/file_manager - removed chromedriver_2.24mac64.zip
[16:19:59] I/file_manager - removed geckodriver-v0.9.0
[16:19:59] I/file_manager - removed geckodriver-v0.9.0-mac.tar.gz
[16:19:59] I/file_manager - removed selenium-server-standalone-2.53.1.jar
```
```
YYY% webdriver-manager update --versions.chrome 2.24
webdriver-manager: using local installed version 10.2.5
[16:20:04] I/downloader - selenium standalone: downloading version 2.53.1
[16:20:04] I/downloader - curl -o /Users/YYY/GitHub/XXX/src/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
[16:20:04] I/downloader - chromedriver: downloading version 2.24
[16:20:04] I/downloader - curl -o /Users/YYY/GitHub/XXX/src/node_modules/webdriver-manager/selenium/chromedriver_2.24mac64.zip https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac64.zip
[16:20:04] I/downloader - geckodriver: downloading version v0.9.0
[16:20:04] I/downloader - curl -o /Users/YYY/GitHub/XXX/src/node_modules/webdriver-manager/selenium/geckodriver-v0.9.0-mac.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.0-mac.tar.gz
[16:20:08] I/update - geckodriver: unzipping /Users/YYY/GitHub/XXX/src/node_modules/webdriver-manager/selenium/geckodriver-v0.9.0-mac.tar.gz
[16:20:08] I/update - geckodriver: setting permissions to 0755 for /Users/YYY/GitHub/XXX/src/node_modules/webdriver-manager/selenium/geckodriver-v0.9.0
[16:20:09] I/update - chromedriver: unzipping /Users/YYY/GitHub/XXX/src/node_modules/webdriver-manager/selenium/chromedriver_2.24mac64.zip
[16:20:09] I/update - chromedriver: setting permissions to 0755 for /Users/YYY/GitHub/XXX/src/node_modules/webdriver-manager/selenium/chromedriver_2.24
```
```
YYY% webdriver-manager status
webdriver-manager: using local installed version 10.2.5
[16:09:39] I/status - selenium standalone version available: 2.53.1 [default]
[16:09:39] I/status - chromedriver version available: 2.24 [default]
[16:09:39] I/status - geckodriver version available: v0.9.0 [default]
[16:09:39] I/status - android-sdk is not present
[16:09:39] I/status - appium is not present
```

However, when running protractor the following happens:
```
YYY% bundle exec rake test:protractor
"EXECUTING: protractor protractorConf.js"
[16:20:30] I/direct - Using ChromeDriver directly...
[16:20:30] I/launcher - Running 1 instances of WebDriver
[16:20:31] E/launcher - session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"9066.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.22.397929 (fb72fb249a903a0b1041ea71eb4c8b3fa0d9be5a),platform=Mac OS X 10.11.6 x86_64)
[16:20:31] E/launcher - SessionNotCreatedError: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"9066.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.22.397929 (fb72fb249a903a0b1041ea71eb4c8b3fa0d9be5a),platform=Mac OS X 10.11.6 x86_64)
    at WebDriverError (/Users/YYY/GitHub/XXX/src/node_modules/selenium-webdriver/lib/error.js:27:5)
    at SessionNotCreatedError (/Users/YYY/GitHub/XXX/src/node_modules/selenium-webdriver/lib/error.js:308:5)
    at Object.checkLegacyResponse (/Users/YYY/GitHub/XXX/src/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/Users/YYY/GitHub/XXX/src/node_modules/selenium-webdriver/http/index.js:538:13)
    at client_.send.then.response (/Users/YYY/GitHub/XXX/src/node_modules/selenium-webdriver/http/index.js:472:11)
    at ManagedPromise.invokeCallback_ (/Users/YYY/GitHub/XXX/src/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/Users/YYY/GitHub/XXX/src/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/Users/YYY/GitHub/XXX/src/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/Users/YYY/GitHub/XXX/src/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    at /Users/YYY/GitHub/XXX/src/node_modules/selenium-webdriver/lib/promise.js:639:7
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/YYY/GitHub/XXX/src/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Driver (/Users/YYY/GitHub/XXX/src/node_modules/selenium-webdriver/chrome.js:778:38)
    at Direct.getNewDriver (/Users/YYY/GitHub/XXX/src/node_modules/protractor/built/driverProviders/direct.js:68:26)
    at Runner.createBrowser (/Users/YYY/GitHub/XXX/src/node_modules/protractor/built/runner.js:198:43)
    at /Users/YYY/GitHub/XXX/src/node_modules/protractor/built/runner.js:277:30
    at _fulfilled (/Users/YYY/GitHub/XXX/src/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/YYY/GitHub/XXX/src/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/YYY/GitHub/XXX/src/node_modules/q/q.js:796:13)
    at /Users/YYY/GitHub/XXX/src/node_modules/q/q.js:556:49
    at runSingle (/Users/YYY/GitHub/XXX/src/node_modules/q/q.js:137:13)
[16:20:31] E/launcher - Process exited with error code 199
"Exit code: 199"
rake aborted!
EXECUTION FAILED: could not start protractor
```

webdriver-manager/config.json:
```
{
  "webdriverVersions": {
    "selenium": "2.53.1",
    "chromedriver": "2.24",
    "geckodriver": "v0.9.0",
    "iedriver": "2.53.1",
    "androidsdk": "24.4.1",
    "appium": "1.5.3"
  },
  "cdnUrls": {
    "selenium": "https://selenium-release.storage.googleapis.com/",
    "chromedriver": "https://chromedriver.storage.googleapis.com/",
    "geckodriver": "https://github.com/mozilla/geckodriver/releases/download/",
    "iedriver": "https://selenium-release.storage.googleapis.com/",
    "androidsdk": "http://dl.google.com/android/"
  }
}
```

**Comment by DarkArc** [comment]
User error, my apologies.

There was an environment configuration issue where both a npm global and local version of protractor were installed at the same time causing the incorrect version to be used. :sweat_smile:

**Comment by SteffyVarghese1** [comment]
@DarkArc : Hi, I how to I resolve this issue because I am also facing the same issue for Android.

**Comment by DarkArc** [comment]
I can't recall for sure, things have changed quite a bit in our setup since this was reported. I think our issue is we believed running npm install was going up update our global install of certain packages. So we actually had to run `npm install -g protractor` for instance.
