### ISSUE TITLE
Investigate Windows issue with webdriver-manager update

### ISSUE THREAD

**Issue by cnishina** [angular/webdriver-manager#123]
Appears to be executing on a `webdriver-manager update`. A quick investigation should be made to verify this behavior:

```
[16:18:53] I/downloader - curl -o C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium/selenium-server-standalone-2.53.1.
e-2.53.1.jar
[16:18:58] I/update - chromedriver: unzipping C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.25win32
fs.js:997
return binding.chmod(pathModule._makeLong(path), modeNum(mode));
^
Error: EPERM: operation not permitted, chmod 'C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver.exe'
at Error (native)
at Object.fs.chmodSync (fs.js:997:18)
```

This error appears to be happening here: https://github.com/angular/webdriver-manager/blob/master/lib/cmds/update.ts#L218

**Comment by vivekbrahmadandi** [comment]
C:\Users\vivekb>webdriver-manager update
[09:20:11] I/file_manager - creating folder C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium
[09:20:11] I/downloader - selenium standalone: downloading version 2.53.1
[09:20:11] I/downloader - curl -o C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium/selenium-server-standalone-2.53.1.jar https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalon
e-2.53.1.jar
[09:20:11] I/downloader - chromedriver: downloading version 2.25
[09:20:11] I/downloader - curl -o C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium/chromedriver_2.25win32.zip https://chromedriver.storage.googleapis.com/2.25/chromedriver_win32.zip
[09:20:11] I/downloader - geckodriver: downloading version v0.9.0
[09:20:11] I/downloader - curl -o C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium/geckodriver-v0.9.0-win64.zip https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.0-win6
4.zip
[09:20:49] I/update - chromedriver: unzipping C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.25win32.zip
fs.js:681
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: ENOENT: no such file or directory, rename 'C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver.exe' -> 'C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdr
iver-manager\selenium\chromedriver_2.25.exe'
    at Error (native)
    at Object.fs.renameSync (fs.js:681:18)
    at unzip (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\built\lib\cmds\update.js:199:8)
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\built\lib\cmds\update.js:160:17
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\built\lib\files\downloader.js:33:17
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\built\lib\files\downloader.js:158:21
    at FSReqWrap.oncomplete (fs.js:82:15)

C:\Users\vivekb>

**Comment by vivekbrahmadandi** [comment]
Can u close this issue?
Its fixed in my local. Antivirus was causing not to install the driver software from repository.
