### ISSUE TITLE
webdriver-manager - node has no method 'isAbsolute'

### ISSUE THREAD

**Issue by MrMic** [angular/webdriver-manager#124]
Hi, 

I am on Mac OSX Sierra and installed protractor and webdriver-manager globally.
Here is what i got with the command line below:

=== 8< ================================== >8 ===

$> webdriver-manager update

/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/built/lib/cmds/update.js:85
        if (path.isAbsolute(options[Opt.OUT_DIR].getString())) {
                 ^
TypeError: Object #<Object> has no method 'isAbsolute'
    at Program.update [as runMethod] (/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/built/lib/cmds/update.js:85:18)
    at Program.run (/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/built/lib/cli/programs.js:60:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/built/lib/webdriver.js:25:38)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/protractor/bin/webdriver-manager:3:1)

=== 8< ============================== >8 ===

can you fix it quickly ???

Thanks for the reply and follow-up.
Rgds,

**Comment by cnishina** [comment]
This looks like a node issue. What version are you using?

**Comment by cnishina** [comment]
Updating this because of this is closed. https://github.com/angular/protractor/issues/3700

**Comment by MrMic** [comment]
Yes, i found that i needed to upgrade node.
