### ISSUE TITLE
10.2.9 requires Node 6

### ISSUE THREAD

**Issue by sime** [angular/webdriver-manager#171]
The 10.2.9 release of webdriver-manager fails on Node v4.5.

I understand v11 requires Node 6, but the 10.2.x branch shouldn't depend on it.

```bash
09:33:32 webdriver-manager: using global installed version 10.2.9
09:33:32 /var/lib/jenkins/jobs/foo/workspace/bar/src/main/node_modules/webdriver-manager/built/lib/cli/logger.js:66
09:33:32     info(...msgs) {
09:33:32          ^^^
09:33:32 
09:33:32 SyntaxError: Unexpected token ...
09:33:32     at exports.runInThisContext (vm.js:53:16)
09:33:32     at Module._compile (module.js:373:25)
09:33:32     at Object.Module._extensions..js (module.js:416:10)
09:33:32     at Module.load (module.js:343:32)
09:33:32     at Function.Module._load (module.js:300:12)
09:33:32     at Module.require (module.js:353:17)
09:33:32     at require (internal/module.js:12:17)
09:33:32     at Object.<anonymous> (/var/lib/jenkins/jobs/gastropad-web/workspace/manager-webapp/src/main/node_modules/webdriver-manager/built/lib/cli/index.js:8:10)
09:33:32     at Module._compile (module.js:409:26)
09:33:32     at Object.Module._extensions..js (module.js:416:10)
```

**Comment by cnishina** [comment]
Resolved with https://github.com/angular/webdriver-manager/issues/170.

**Comment by cnishina** [comment]
Please see instructions in #170 and use that thread for any on going issues with this topic.
