### ISSUE TITLE
"webdriver-manager update --android" installs image without Chrome browser

### ISSUE THREAD

**Issue by finspin** [angular/webdriver-manager#193]
I tried installing Android emulator with the following commands on macOS:

`webdriver-manager update --android`
`webdriver-manager update --android --android-api-levels 24 --android-archs x86_64`

In both cases, the emulator that is installed doesn't have Chrome installed.

**Launch emulator:**

    my-mac:DEV me$ webdriver-manager start --android
    [16:06:43] I/start - Booting up AVD android-24-default-x86_64
    [16:06:43] I/start - Starting appium server
    [16:06:43] I/start - java -Dwebdriver.chrome.driver=/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.25 -Dwebdriver.gecko.driver=/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.9.0 -jar /usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar
    [16:06:43] I/start - seleniumProcess.pid: 24089
    16:06:43.764 INFO - Launching a standalone Selenium Server
    16:06:43.867 INFO - Java: Oracle Corporation 25.92-b14
    16:06:43.867 INFO - OS: Mac OS X 10.11.2 x86_64
    16:06:43.912 INFO - v2.53.1, with Core v2.53.1. Built from revision a36b8b1
    16:06:44.380 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
    registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
    16:06:44.381 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
    registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
    16:06:44.383 INFO - Driver class not found: com.opera.core.systems.OperaDriver
    16:06:44.383 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
    16:06:44.388 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
    16:06:44.388 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
    Hax is enabled
    Hax ram_size 0x40000000
    HAX is working and emulator runs in fast virt mode.
    16:06:44.592 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
    16:06:44.593 INFO - Selenium Server is up and running
    emulator: Listening for console connections on port: 5554
    emulator: Serial number of this emulator (for ADB): emulator-5554

**Start test:**

    my-mac:DEV me$ protractor test-configs/appium-conf.js --specs=tests/_sandbox/basic-test.js 
    (node:24116) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
    [16:11:03] I/hosted - Using the selenium server at http://localhost:4723/wd/hub
    [16:11:03] I/launcher - Running 1 instances of WebDriver
    [16:11:04] E/launcher - An unknown server-side error occurred while processing the command. Original error: Could not find package com.android.chrome on the device
    [16:11:04] E/launcher - WebDriverError: An unknown server-side error occurred while processing the command. Original error: Could not find package com.android.chrome on the device
        at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
        at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:538:13)
        at client_.send.then.response (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:472:11)
        at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25)
        at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)
    From: Task: WebDriver.createSession()
        at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
        at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:458:24)
        at Hosted.DriverProvider.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/driverProvider.js:37:33)
        at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:198:43)
        at /usr/local/lib/node_modules/protractor/built/runner.js:285:30
        at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
        at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
        at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
        at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:556:49
        at runSingle (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:137:13)
    [16:11:04] E/launcher - Process exited with error code 199

**Comment by sjelin** [comment]
This is extremely odd, since we have [e2e tests](https://github.com/angular/webdriver-manager/blob/master/e2e_spec/android_spec.ts) which boot up chrome on android.  I'd love to dig into this problem for you, but sadly I've been transferred to another team 😢
