### ISSUE TITLE
webdriver-manager update keeps giving an error

### ISSUE THREAD

**Issue by ashwinawake** [angular/webdriver-manager#209]
After I install protractor, I run webdriver-manager update and throws this exception pated below. What am I doing wrong here? Any help will be appreciated. Thanks.

```/Users/ash/.nvm/versions/node/v5.6.0/lib/node_modules/protractor/node_modules/webdriver-manager/built/lib/cli/logger.js:66
    info(...msgs) {
         ^^^
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/ashwinraju_TWC/.nvm/versions/node/v5.6.0/lib/node_modules/protractor/node_modules/webdriver-manager/built/lib/cli/index.js:8:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)```

**Comment by cnishina** [comment]
Duplicate issue. Please see the answer here. https://github.com/angular/webdriver-manager/issues/170
