### ISSUE TITLE
Issue starting Webdriver-Manager Java Version Issue?

### ISSUE THREAD

**Issue by ozarka30** [angular/webdriver-manager#213]
I had webdriver-manager working for my angular test, but recently I started getting the error below.
I think it might be a java issue? Is the current webdriver version compatible with java 7?
I'm currently running versions:
     java: 1.7.0
     webdriver-manager 12.0.2
     selenium standalone 3.1.0
     chromedriver 2.27
     geckodriver v0.14.0 

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE003 ba
d major version; class=org/openqa/grid/selenium/GridLauncherV3, offset=6
        at java.lang.ClassLoader.defineClassImpl(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:364)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:15
4)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:777)
        at java.net.URLClassLoader.access$400(URLClassLoader.java:96)
        at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1225)
        at java.security.AccessController.doPrivileged(AccessController.java:366
)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:660)
        at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:942)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:851)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:827)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:494)
```

**Comment by cnishina** [comment]
A quick google search on your error says something about either a mismatch in Java runtime environment version or to use openjdk. I'm not sure which one you should try but this is a support issue and should be directed to StackOverflow.

Closing this issue.
