### ISSUE TITLE
--start-signifier polls Appium instead of Selenium before signaling

### ISSUE THREAD

**Issue by mikeperri** [angular/webdriver-manager#227]
It looks like the --start-signifier option doesn't work correctly because the signalWhenReady function uses the `appiumPort` variable where it should be polling the Selenium server. I changed it to `seleniumPort` and was able to use the start signifier, both in the mode where it's printed to stdout, and using IPC.

I tried writing a test for the start command to cover this, but the existing tests didn't pass on either Mac or Windows 10. 

Here's some of my test output:
```
[13:22:51] Starting 'test:unit'...
webdriver-manager: using project version 12.0.4
Started
.[13:22:52] I/update - appium: installing appium
........................................[13:23:08] I/update - android-sdk: file exists /Users/mperri/dev/webdriver-manager/selenium/android-sdk_r24.4.1-macosx.zip
F.F[13:23:19] I/update - android-sdk: unzipping android-sdk_r24.4.1-macosx.zip
F....................................

Failures:
1) status should show the version number of the default and latest versions
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:365:14)
        at tryOnTimeout (timers.js:237:5)
        at Timer.listOnTimeout (timers.js:207:5)
  Message:
    Expected ' 2.44.0' to contain '2.44.0 [last]'.
  Stack:
    Error: Expected ' 2.44.0' to contain '2.44.0 [last]'.
        at Object.it (/Users/mperri/dev/webdriver-manager/built/spec/cmds/status_spec.js:63:46)
  Message:
    Expected 1 to equal 2.
  Stack:
    Error: Expected 1 to equal 2.
        at Object.it (/Users/mperri/dev/webdriver-manager/built/spec/cmds/status_spec.js:65:48)
  Message:
    Expected ' 2.24' to contain '2.20 [last]'.
  Stack:
    Error: Expected ' 2.24' to contain '2.20 [last]'.
        at Object.it (/Users/mperri/dev/webdriver-manager/built/spec/cmds/status_spec.js:66:44)
  Message:
    Expected undefined to contain '2.24'.
  Stack:
    Error: Expected undefined to contain '2.24'.
        at Object.it (/Users/mperri/dev/webdriver-manager/built/spec/cmds/status_spec.js:67:44)

2) update for update-config.json should create a file for standalone
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:365:14)
        at tryOnTimeout (timers.js:237:5)
        at Timer.listOnTimeout (timers.js:207:5)

3) downloader get file should download a file with mismatch content length
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:365:14)
        at tryOnTimeout (timers.js:237:5)
        at Timer.listOnTimeout (timers.js:207:5)

81 specs, 3 failures
Finished in 32.359 seconds

[13:23:25] 'test:unit' errored after 34 s
[13:23:25] Error: 1
    at formatError (/Users/mperri/dev/webdriver-manager/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/mperri/dev/webdriver-manager/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/mperri/dev/webdriver-manager/node_modules/orchestrator/index.js:264:8)
    at /Users/mperri/dev/webdriver-manager/node_modules/orchestrator/index.js:275:23
    at finish (/Users/mperri/dev/webdriver-manager/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/mperri/dev/webdriver-manager/node_modules/orchestrator/lib/runTask.js:29:3)
    at ChildProcess.<anonymous> (/Users/mperri/dev/webdriver-manager/gulpfile.js:15:7)
    at emitTwo (events.js:106:13)
[13:23:25] 'test:e2e' errored after 44 s
[13:23:25] Error in plugin 'run-sequence(test:unit)'
Error
    at finish (/Users/mperri/dev/webdriver-manager/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/Users/mperri/dev/webdriver-manager/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/mperri/dev/webdriver-manager/node_modules/orchestrator/index.js:264:8)
    at /Users/mperri/dev/webdriver-manager/node_modules/orchestrator/index.js:275:23
    at finish (/Users/mperri/dev/webdriver-manager/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/mperri/dev/webdriver-manager/node_modules/orchestrator/lib/runTask.js:29:3)
    at ChildProcess.<anonymous> (/Users/mperri/dev/webdriver-manager/gulpfile.js:15:7)
    at emitTwo (events.js:106:13)
[13:23:39] I/update - android-sdk: setting permissions to 0755 for /Users/mperri/dev/webdriver-manager/selenium/android-sdk_r24.4.1
[13:23:39] I/update - android-sdk: android-sdk_r24.4.1 up to date
[13:23:39] I/update - android-sdk: Downloading additional SDK updates
```
It looked like the promise returned by the "update" program was being resolved too early, before all of the installers finished, which would then cause the tests to time out.

**Comment by cnishina** [comment]
Closed with https://github.com/angular/webdriver-manager/pull/228
