### ISSUE TITLE
webdriver-manager start command returns certificate error

### ISSUE THREAD

**Issue by parky128** [angular/webdriver-manager#250]
I am no longer able to start up an instance of selenium server using the `webdriver-manager start` command as I am encountering the following error:

```
C:\>webdriver-manager start
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
```

I have the latest version of webdriver-manager installed 12.0.5.

This was running for me fine last week, but since yesterday this problem has crept in.

I see someone else with the same issue has posted a question over at [SO](http://stackoverflow.com/questions/42995459/webdriver-manager-start-certificate-error/43597318?noredirect=1#comment74827437_43597318) but I don't like the sound of having re-install protractor each time as they say they are currently having to do to get around this issue.

Does anyone know what could be the problem here?

Thanks

**Comment by cnishina** [comment]
Could you double check the `webdriver-manager version` that you are using? I'm using 12.0.5 installed globally and it does not have this issue. Version 12.0.5 does not any web request externally so this `Error: unable to get local issuer certificate` potentially makes me believe you are using an older version.

How you can check your version:

```
>: webdriver-manager version   
                                                                                                                    
webdriver-manager: using global installed version 12.0.5
[08:42:09] I/version - webdriver-manager 12.0.5
```

On start should work without internet. I just tried it on my Windows home computer and was able to run `start` without internet access. Also works on my Mac.

```
>: webdriver-manager start

webdriver-manager: using global installed version 12.0.5
[08:20:24] I/start - java -Dwebdriver.chrome.driver=/Users/cnishina/.nvm/versions/node/v6.9.4/lib/node_modules/webdriver-manager/selenium/chromedriver_2.29 -Dwebdriver.gecko.driver=/Users/cnishina/.nvm/versions/node/v6.9.4/lib/node_modules/webdriver-manager/selenium/geckodriver-v0.16.1 -jar /Users/cnishina/.nvm/versions/node/v6.9.4/lib/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.4.0.jar -port 4444
[08:20:24] I/start - seleniumProcess.pid: 71748
08:20:24.833 INFO - Selenium build info: version: '3.4.0', revision: 'unknown'
08:20:24.834 INFO - Launching a standalone Selenium Server
2017-05-10 08:20:24.861:INFO::main: Logging initialized @433ms to org.seleniumhq.jetty9.util.log.StdErrLog
08:20:24.938 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
08:20:24.938 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
08:20:24.939 INFO - Driver class not found: com.opera.core.systems.OperaDriver
08:20:24.939 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
08:20:24.939 INFO - Driver class not found: com.opera.core.systems.OperaDriver
08:20:24.939 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
2017-05-10 08:20:24.999:INFO:osjs.Server:main: jetty-9.4.3.v20170317
2017-05-10 08:20:25.045:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@d8355a8{/,null,AVAILABLE}
2017-05-10 08:20:25.087:INFO:osjs.AbstractConnector:main: Started ServerConnector@146ba0ac{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2017-05-10 08:20:25.087:INFO:osjs.Server:main: Started @660ms
08:20:25.088 INFO - Selenium Server is up and running
```

**Comment by parky128** [comment]
I checked my version as you have suggested and it is showing as 12.0.5

I have since uninstalled and re-installed protractor, ran `webdriver-manager update` to re-install the browser drivers and now selenium server starts up again for me.

I noticed that I am now on version 12.0.6 which I can see got bumped a couple of days ago.

**Comment by cnishina** [comment]
And it still does not work?

**Comment by cnishina** [comment]
Also, could you try webdriver-manager versions 12.0.3 and 12.0.4? We made some changes around proxy and ignore_ssl and want to rule those out. Thanks!

**Comment by parky128** [comment]
@cnishina 

Well this is getting weird now, so I downgraded from 12.0.6 to 12.0.4, and got my selenium server running just fine.

Then after exiting the server and restarting it a few times via the usual `webdriver-manager start` I am now getting this:

```
webdriver-manager: using global installed version 12.0.4
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
```

I bet if I were to reinstall 12.0.6 the problem would go away again, but only for a short amount of time.

**Comment by cnishina** [comment]
Please try and update this issue.

**Comment by parky128** [comment]
@cnishina 

So I ended up upgrading from 12.0.4 to 12.0.5 and was able to start my selenium server fine again.

I have actually left it running all day yesterday and into this morning. I happened to ctrl+c to exit out the console it was running from, and tried a new webdriver-manager start command and I get the same error as before when I was on 12.0.4:

```
C:\Users\rparker>webdriver-manager start
webdriver-manager: using global installed version 12.0.5
[08:36:50] I/start - java -Dwebdriver.chrome.driver=C:\Users\rparker\AppData\Roa
ming\npm\node_modules\webdriver-manager\selenium\chromedriver_2.29.exe -Dwebdriv
er.ie.driver=C:\Users\rparker\AppData\Roaming\npm\node_modules\webdriver-manager
\selenium\IEDriverServer3.4.0.exe -Dwebdriver.gecko.driver=C:\Users\rparker\AppD
ata\Roaming\npm\node_modules\webdriver-manager\selenium\geckodriver-v0.16.1.exe
-jar C:\Users\rparker\AppData\Roaming\npm\node_modules\webdriver-manager\seleniu
m\selenium-server-standalone-3.4.0.jar -port 4444
[08:36:50] I/start - seleniumProcess.pid: 10844
08:36:51.167 INFO - Selenium build info: version: '3.4.0', revision: 'unknown'
08:36:51.168 INFO - Launching a standalone Selenium Server
2017-05-23 08:36:51.192:INFO::main: Logging initialized @298ms to org.seleniumhq
.jetty9.util.log.StdErrLog
08:36:51.246 INFO - Driver class not found: com.opera.core.systems.OperaDriver
08:36:51.246 INFO - Driver provider com.opera.core.systems.OperaDriver registrat
ion is skipped:
Unable to create new instances on this machine.
08:36:51.246 INFO - Driver class not found: com.opera.core.systems.OperaDriver
08:36:51.247 INFO - Driver provider com.opera.core.systems.OperaDriver is not re
gistered
08:36:51.248 INFO - Driver provider org.openqa.selenium.safari.SafariDriver regi
stration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform
=MAC}] does not match the current platform VISTA
2017-05-23 08:36:51.290:INFO:osjs.Server:main: jetty-9.4.3.v20170317
2017-05-23 08:36:51.333:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletC
ontextHandler@d8355a8{/,null,AVAILABLE}
2017-05-23 08:36:51.447:INFO:osjs.AbstractConnector:main: Started ServerConnecto
r@5f2108b5{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2017-05-23 08:36:51.448:INFO:osjs.Server:main: Started @555ms
08:36:51.448 INFO - Selenium Server is up and running
[11:25:08] I/start - Staying alive until the Selenium Standalone process exits
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:572:26)
Terminate batch job (Y/N)? y

C:\Users\rparker>webdriver-manager start
webdriver-manager: using global installed version 12.0.5
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
```

**Comment by kylesb** [comment]
I was having the same issues after starting `webdriver-manager` on one network, then transferring my machine over to a separate, private network. 

I was able to resolve starting Selenium server by simply cleaning 

> webdriver-manager shutdown
> webdriver-manager clean # run this after you stop or restart the Selenium server
> web

**Comment by kylesb** [comment]
I was having a similar issue after starting webdriver-manager on one network, then transferring my machine over to a separate, private network.

I was able to resolve starting Selenium server by simply cleaning and using the `ignore_ssl` flag.

```bash
webdriver-manager shutdown
webdriver-manager clean # remove the downloaded driver files 
webdriver-manager update --ignore_ssl # bypass network proxy
webdriver-manager start 
```

**Comment by tschechniker** [comment]
Hi,

i have the same Problem with 12.0.6. When i downgrade to 12.0.5 it works

**Comment by light24bulbs** [comment]
@kylesb I am also having this issue when moving the same install to a different environment.  Locally I do --ignore_ssl, but when I push the container to a remote environment without internet access and try to start it, it hangs waiting for the network

**Comment by cnishina** [comment]
Please try this again. 13 should not make any requests that require certs. If this is still an issue, please open up a new one. Thanks!
