### ISSUE TITLE
webdriver-manager update: connect ECONNREFUSED 173.194.221.128:443

### ISSUE THREAD

**Issue by MarkAvreliy** [angular/webdriver-manager#252]
Hello.

I have a problem with webdriver-manager update:
```
>webdriver-manager version
[15:18:49] I/version - webdriver-manager 12.0.6
>webdriver-manager update
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 173.194.221.128:443
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
```

tracert is:
```
Tracing route to lm-in-f128.1e100.net [173.194.221.128]
over a maximum of 30 hops:

  1     7 ms     5 ms     3 ms  10.233.26.2
  2     2 ms     2 ms     1 ms  145.255.238.129
  3     2 ms     1 ms     1 ms  172.16.98.36
  4     4 ms     4 ms     4 ms  172.16.100.254
  5     4 ms     4 ms     4 ms  172.16.100.252
  6     2 ms     2 ms     1 ms  172.16.100.250
  7     3 ms     3 ms     2 ms  79.142.92.103
  8    31 ms    15 ms    15 ms  193.106.112.103
  9    11 ms    11 ms    12 ms  google-gw.rascom.as20764.net [81.27.254.18]
 10    11 ms    10 ms    11 ms  72.14.233.106
 11    18 ms    18 ms    18 ms  64.233.174.85
 12    27 ms    24 ms    26 ms  74.125.37.253
 13     *        *        *     Request timed out.
 14     *        *        *     Request timed out.
 15     *        *        *     Request timed out.
 16     *        *        *     Request timed out.
 17     *        *        *     Request timed out.
 18     *        *        *     Request timed out.
 19     *        *        *     Request timed out.
 20     *        *        *     Request timed out.
 21     *        *        *     Request timed out.
 22     *        *        *     Request timed out.
 23    28 ms    28 ms    28 ms  lm-in-f128.1e100.net [173.194.221.128]
```

what's wrong? where i have to check a reason? But i think a reason in outside server (173.194.221.128).

**Comment by MarkAvreliy** [comment]
now i get problem here _Error: connect ECONNREFUSED 172.217.22.176:443_
IP address hanges.

**Comment by cnishina** [comment]
Hmm.... weird. Has webdriver-manager worked for you in the past? What was the last version that worked? Could you try webdriver-manager versions 12.0.3 and 12.0.4? We made some changes around proxy and ignore_ssl and want to rule those out. Thanks!

**Comment by MarkAvreliy** [comment]
Hello, cnishina.
It's my first time protractor installing.
So i use npm -> protractor install -> webdriver-manager update (for selenium).
I just tried to do step by step as it written here: https://www.youtube.com/watch?v=57134cHJlAs
or here: http://www.protractortest.org/#/tutorial
step: webdriver-manager update
All is the newest one.

**Comment by pyalam01** [comment]
Hi cnishina : I tried executing webdriver-manager update command with and without ignore_ssl flag on both versions (12.0.3 and 12.0.4) of webdriver-manager and getting "unhandled error event" & "ETIMEDOUT error with different IP addresses. I did a tracert for the displayed IP addresses and request is timing out at destination IP servers. 

PS C:\Users\XXXXX\AppData\Roaming\npm> webdriver-manager update	
webdriver-manager: using global installed version 12.0.3
[10:30:04] I/file_manager - creating folder C:\Users\XXXXXX\AppData\Roaming\npm\node_modules\webdriver-manager\selenium

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: connect ETIMEDOUT 192.30.253.117:443
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
	
PS C:\Users\XXXXX\AppData\Roaming\npm> webdriver-manager update --ignore_ssl
webdriver-manager: using global installed version 12.0.3
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: connect ETIMEDOUT 172.217.6.112:443
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

PS C:\Users\XXXXXX\AppData\Roaming\npm> webdriver-manager update
webdriver-manager: using global installed version 12.0.4
[10:41:25] I/file_manager - creating folder C:\Users\XXXXX\AppData\Roaming\npm\node_modules\webdriver-manager\selenium

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: connect ETIMEDOUT 172.217.6.112:443
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

	
PS C:\Users\XXXXXXX\AppData\Roaming\npm> webdriver-manager update --ignore_ssl
webdriver-manager: using global installed version 12.0.4
[10:42:25] I/http_utils - ignoring SSL certificate
[10:42:25] I/http_utils - ignoring SSL certificate
[10:42:25] I/http_utils - ignoring SSL certificate
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: connect ETIMEDOUT 172.217.6.112:443
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

Tracert log for the above IP addresses:

C:\Users\A591572>tracert 192.30.253.117
Tracing route to 192.30.253.117 over a maximum of 30 hops
  1     1 ms     1 ms     1 ms  t9381swt0006_vlan10.target.com [10.92.54.1]
  2    <1 ms    <1 ms    <1 ms  t9381distswt0101_gi1-22.target.com [10.92.1.209]

  3     3 ms     3 ms     3 ms  10.93.248.49
  4     4 ms     3 ms     3 ms  targetindiacluster.target.com [10.93.128.124]
  5     4 ms     4 ms     3 ms  t9357inetswt001.target.com [10.93.128.17]
  6     8 ms     7 ms     8 ms  125.16.224.201
  7    41 ms    41 ms    42 ms  182.79.255.22
  8    45 ms    44 ms    44 ms  xe-0-1-0-9.r00.sngpsi05.sg.bb.gin.ntt.net [116.5
1.27.181]
  9    42 ms    43 ms    42 ms  ae-10.r20.sngpsi05.sg.bb.gin.ntt.net [129.250.7.
18]
 10   234 ms   234 ms   234 ms  ae-8.r22.snjsca04.us.bb.gin.ntt.net [129.250.3.4
8]
 11   298 ms   298 ms   298 ms  ae-7.r23.asbnva02.us.bb.gin.ntt.net [129.250.6.2
38]
 12   303 ms   303 ms   303 ms  ae-20.r06.asbnva02.us.bb.gin.ntt.net [129.250.2.
133]
 13   287 ms   286 ms   287 ms  ae-1.a03.asbnva02.us.bb.gin.ntt.net [129.250.5.2
14]
 14   272 ms   271 ms   271 ms  xe-0-0-24-1.a03.asbnva02.us.ce.gin.ntt.net [128.
241.3.30]
 15     *        *        *     Request timed out.
 16     *        *        *     Request timed out.
 17   263 ms   263 ms   263 ms  192.30.253.117
Trace complete.

C:\Users\A591572>tracert 172.217.6.112
Tracing route to 172.217.6.112 over a maximum of 30 hops
  1     1 ms     1 ms     1 ms  t9381swt0006_vlan10.target.com [10.92.54.1]
  2    <1 ms    <1 ms    <1 ms  t9381distswt0101_gi1-22.target.com [10.92.1.209]
  3     3 ms     3 ms     6 ms  10.93.248.49
  4     3 ms     3 ms     3 ms  targetindiacluster.target.com [10.93.128.124]
  5     5 ms     3 ms     3 ms  t9357inetswt001.target.com [10.93.128.17]
  6    11 ms     6 ms     8 ms  125.16.224.201
  7    25 ms    10 ms    10 ms  182.79.232.169
  8    12 ms    12 ms    11 ms  72.14.242.178
  9    16 ms    10 ms    11 ms  216.239.56.32
 10    44 ms    44 ms    44 ms  216.239.48.227
 11   119 ms   119 ms   119 ms  209.85.255.129
 12   206 ms   206 ms   206 ms  209.85.142.51
 13   209 ms   210 ms   209 ms  72.14.238.84
 14   256 ms   256 ms   256 ms  72.14.233.110
 15   258 ms   255 ms   255 ms  209.85.251.240
 16     *        *        *     Request timed out.
 17   252 ms   252 ms   252 ms  108.170.238.91
 18   248 ms   248 ms   249 ms  172.217.6.112

Trace complete.

**Comment by cnishina** [comment]
Could you try the following? Change the `/path/to/webdriver-manager/selenium`. This could be any folder path. What we are testing is the web calls that webdriver-manager does.

## On response retrieval:

```
curl -o /path/to/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
curl -o /path/to/webdriver-manager/selenium/standalone-response.xml https://selenium-release.storage.googleapis.com/
curl -o /path/to/webdriver-manager/selenium/gecko-response.json https://api.github.com/repos/mozilla/geckodriver/releases
```

## On download:

```
curl -o /path/to/webdriver-manager/selenium/chromedriver_2.29.zip https://chromedriver.storage.googleapis.com/2.29/chromedriver_mac64.zip
curl -o /path/to/webdriver-manager/selenium/selenium-server-standalone-3.4.0.jar https://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar
curl -o /path/to/webdriver-manager/selenium/geckodriver-v0.16.1.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-macos.tar.gz
```

**Comment by pyalam01** [comment]
@cnishina : All the above web calls are timed out. 
![curl manual execution output](https://cloud.githubusercontent.com/assets/28562577/26189976/cc7b6ac8-3bc4-11e7-927a-1537fff351a6.png)

**Comment by cnishina** [comment]
Hmmm.. well, do you have a proxy that you are using? If all the hosts timeout, something must be happening on your end.

**Comment by pyalam01** [comment]
I tried with and without proxy too, same result.

**Comment by cnishina** [comment]
So there was a release on April 24th for 12.0.5 and May 9th there was a release for 12.0.6. So 12.0.5 should work then. Try again 12.0.4 and 12.0.5. Also remove the entire node_modules folder to clear out the `webdriver-manager/selenium` folder.

**Comment by pyalam01** [comment]
I uninstalled whole node/npm setup and re-installed 12.0.4 and 12.0.5 versions, still no luck. It gives "unhandled error event" error with ETIMEDOUT 172.217.1.48. I did a tracert to the IP and its getting timedout at one point. Could you pls investigate if that is the source of the issue.

C:\Users>tracert 172.217.1.48
Tracing route to 172.217.1.48 over a maximum of 30 hops

  1     1 ms     1 ms     1 ms  xxxxxxxxxx.yyyyy.com [IP]
  2    <1 ms    <1 ms    <1 ms  xxxxxxxxxx.yyyyy.com [IP]
  3     2 ms     2 ms     2 ms  73.XX.409.YY
  4     3 ms     2 ms     2 ms  xxxxxxxxxx.yyyyy.com [IP]
  5     3 ms     3 ms     3 ms  xxxxxxxxxx.yyyyy.com [IP]
  6     7 ms     7 ms     7 ms  135.10.254.242
  7    17 ms    10 ms    10 ms  123.241.134.255
  8    10 ms    10 ms    10 ms  72.23.242.178
  9    10 ms    10 ms    10 ms  66.249.94.73
 10    50 ms    43 ms    53 ms  209.85.268.251
 11   113 ms   113 ms   128 ms  209.85.247.135
 12   196 ms   198 ms   196 ms  209.85.142.49
 13   205 ms   215 ms   205 ms  72.14.239.13
 14   246 ms   258 ms   246 ms  72.14.239.208
 15   237 ms   237 ms   237 ms  209.85.246.194
 16     *        *        *     Request timed out.
 17   247 ms   247 ms   246 ms  216.239.41.163
 18   238 ms   238 ms   238 ms  172.217.1.48

Trace complete.

**Comment by cnishina** [comment]
I am having issues downloading geckodriver from github with a proxy.

```
Message:
    Error: tunneling socket could not be established, cause=socket hang up
  Stack:
    Error: tunneling socket could not be established, cause=socket hang up
        at ClientRequest.onError (/Users/cnishina/src/proxy-server/node_modules/tunnel-agent/index.js:177:17)
        at ClientRequest.g (events.js:291:16)
        at emitOne (events.js:96:13)
        at ClientRequest.emit (events.js:188:7)
        at Socket.socketOnEnd (_http_client.js:346:9)
        at emitNone (events.js:91:20)
        at Socket.emit (events.js:185:7)
        at endReadableNT (_stream_readable.js:974:12)
        at _combinedTickCallback (internal/process/next_tick.js:74:11)
        at process._tickCallback (internal/process/next_tick.js:98:9)
```

Could you try:

`webdriver-manager update --gecko false --ignore_ssl --proxy http://proxy----`

**Comment by pyalam01** [comment]
Hi - 'update' command downloads selenium, chromedriver, geckodriver binaries if and only if you send @ignoressl and @proxy flags. I was not having any problem downloading geckodriver with proxy. However, 'webdriver-manager start' command runs chromedriver and selenium server only for the very first time and not later. I verified this by sending ctrl+c - job got terminated and how many ever times I execute 'webdriver-manager start', it shows "unhandled error event".

**Comment by konstantinblaesi** [comment]
Problem solved on Windows 10 :
```
set HTTP_PROXY=http://host:port
set HTTPS_PROXY=http://host:port
```

**Comment by UpekshaJayaweera** [comment]
Hi Any one know how to resolved this problem?
10:39:36.790 [GENIE] io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:684)evel: There was an error managing chromedriver (latest version) (Connect to chromedriver.storage.googleapis.com:443 [chromedriver.storage.googleapis.com/172.217.194.128] failed: Connection timed out: connect) ... trying again using cache and mirrorsg

**Comment by konstantinblaesi** [comment]
Yes figure out why your network blocks https connections to googles servers. In corporate environments you may need to use a proxy or ask someone to whitelist domains. Check with your browser if you can access https://chromedriver.storage.googleapis.com

**Comment by cnishina** [comment]
Docs related.

**Comment by SidV7** [comment]
@cnishina
ok, so i was able to run these commands in corporate network
webdriver-manager update --proxy=http://xxx.xxx.xxx:8080
webdriver-manager start --proxy=http://xxx.xxx.xxx:8080
The binaries got downloaded and the selenium server started on 4444. But now when i'm trying to run the test cases
npm run e2e - getting the TIMEOUT error but don't face this error outside VPN. Do i need to invoke npm run e2e differently?

C:\Users\xxx\Workspace\Angular\angular-with-cucumber>npm run e2e

    angular-with-cucumber@0.0.0 e2e C:\Users\xxx\Workspace\Angular\angular-with-cucumber
    ng e2e

[16:02:15] I/config_source - curl -oC:\Users\xxx\Workspace\Angular\angular-with-cucumber\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
events.js:288
throw er; // Unhandled 'error' event
^

Error: connect ETIMEDOUT 172.217.9.16:443
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
Emitted 'error' event on Request instance at:
at Request.onRequestError (C:\Users\xxx\Workspace\Angular\angular-with-cucumber\node_modules\request\request.js:877:8)
at ClientRequest.emit (events.js:323:22)
at TLSSocket.socketErrorListener (_http_client.js:426:9)
at TLSSocket.emit (events.js:311:20)
at emitErrorNT (internal/streams/destroy.js:92:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
at processTicksAndRejections (internal/process/task_queues.js:84:21) {
errno: 'ETIMEDOUT',
code: 'ETIMEDOUT',
syscall: 'connect',
address: '172.217.9.16',
port: 443
}

**Comment by akbbhatt** [comment]
> @cnishina
> ok, so i was able to run these commands in corporate network
> webdriver-manager update --proxy=http://xxx.xxx.xxx:8080
> webdriver-manager start --proxy=http://xxx.xxx.xxx:8080
> The binaries got downloaded and the selenium server started on 4444. But now when i'm trying to run the test cases
> npm run e2e - getting the TIMEOUT error but don't face this error outside VPN. Do i need to invoke npm run e2e differently?
> 
> C:\Users\xxx\Workspace\Angular\angular-with-cucumber>npm run e2e
> 
> ```
> angular-with-cucumber@0.0.0 e2e C:\Users\xxx\Workspace\Angular\angular-with-cucumber
> ng e2e
> ```
> 
> [16:02:15] I/config_source - curl -oC:\Users\xxx\Workspace\Angular\angular-with-cucumber\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
> events.js:288
> throw er; // Unhandled 'error' event
> ^
> 
> Error: connect ETIMEDOUT 172.217.9.16:443
> at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
> Emitted 'error' event on Request instance at:
> at Request.onRequestError (C:\Users\xxx\Workspace\Angular\angular-with-cucumber\node_modules\request\request.js:877:8)
> at ClientRequest.emit (events.js:323:22)
> at TLSSocket.socketErrorListener (_http_client.js:426:9)
> at TLSSocket.emit (events.js:311:20)
> at emitErrorNT (internal/streams/destroy.js:92:8)
> at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
> at processTicksAndRejections (internal/process/task_queues.js:84:21) {
> errno: 'ETIMEDOUT',
> code: 'ETIMEDOUT',
> syscall: 'connect',
> address: '172.217.9.16',
> port: 443
> }

Did you find a solution for this? I am having the exact same issue.

**Comment by konstantinblaesi** [comment]
@akbbhatt Are you in a corporate environment? It is not uncommon to tunnel connections to the internet through a proxy. You need to configure this proxy either locally per application or globally for your operating system.
