### ISSUE TITLE
webdriver-manager unable to start chrome on Debian 8 (Jessie) via xvfb-run

### ISSUE THREAD

**Issue by M3ssman** [angular/webdriver-manager#255]
Hi there,

I'm struggeling with a headless ng Test Suite on a Debian 8 Host (let's call it a Jenkins Container).
Trying to start it via Protractor results into: 

```
jenkins@f0472fcc28b8:~/ticketsystem-client$ xvfb-run node_modules/.bin/protractor protractor.conf.js 
[11:31:59] I/launcher - Running 1 instances of WebDriver
[11:31:59] I/direct - Using ChromeDriver directly...
[11:33:00] E/launcher - unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-78-generic x86_64)
[11:33:00] E/launcher - WebDriverError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-78-generic x86_64)
    at WebDriverError (/var/jenkins_home/ticketsystem-client/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/var/jenkins_home/ticketsystem-client/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/var/jenkins_home/ticketsystem-client/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/var/jenkins_home/ticketsystem-client/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/var/jenkins_home/ticketsystem-client/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/var/jenkins_home/ticketsystem-client/node_modules/selenium-webdriver/chrome.js:709:29)
    at Direct.getNewDriver (/var/jenkins_home/ticketsystem-client/node_modules/protractor/lib/driverProviders/direct.ts:90:25)
    at Runner.createBrowser (/var/jenkins_home/ticketsystem-client/node_modules/protractor/lib/runner.ts:225:39)
    at q.then.then (/var/jenkins_home/ticketsystem-client/node_modules/protractor/lib/runner.ts:391:27)
    at _fulfilled (/var/jenkins_home/ticketsystem-client/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/var/jenkins_home/ticketsystem-client/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/var/jenkins_home/ticketsystem-client/node_modules/protractor/node_modules/q/q.js:796:13)
    at /var/jenkins_home/ticketsystem-client/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/var/jenkins_home/ticketsystem-client/node_modules/protractor/node_modules/q/q.js:137:13)
[11:33:00] E/launcher - Process exited with error code 199
```

Installed are Google Chrome 58.0.3029.110, xvfb 2:1.16.4-1 and webdriver-manager 12.0.6

**Comment by cnishina** [comment]
This is probably a ChromeDriver issue and should be [filed against ChromeDriver](https://sites.google.com/a/chromium.org/chromedriver/help). Also, since you are starting ChromeDriver directly, this is not an issue for webdriver-manager.

Anyway, without leaving you empty handed...from my personal Jenkins server, I reran my tests and have the following console output:

console log chrome version:
```
+ google-chrome --version
Google Chrome 58.0.3029.110 
```

snippet from the actual test:

```
webdriver-manager update --standalone false --gecko false

[17:54:27] I/update - chromedriver: file exists /var/lib/jenkins/workspace/testing_angular_applications_8_1/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.29.zip
[17:54:27] I/update - chromedriver: unzipping chromedriver_2.29.zip
[17:54:27] I/update - chromedriver: setting permissions to 0755 for /var/lib/jenkins/workspace/testing_angular_applications_8_1/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.29
[17:54:27] I/update - chromedriver: chromedriver_2.29 up to date

> chapter-8-starter@0.0.0 e2e /var/lib/jenkins/workspace/testing_angular_applications_8_1
> protractor "test-8-1.conf.js"
(node:28950) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[17:54:28] I/launcher - Running 1 instances of WebDriver
[17:54:28] I/direct - Using ChromeDriver directly...
Started
.


1 spec, 0 failures
Finished in 1.826 seconds

[17:54:31] I/launcher - 0 instance(s) of WebDriver still running
[17:54:31] I/launcher - chrome #01 passed
Xvfb stopping
```

You can read more about how I set up my Jenkins tests here: https://medium.com/@cnishina/protractor-in-ci-jenkins-6f5fd3fc06ee

If you want to run tests with xvfb-run, I was able to also kick that off in a different project on CircleCI beta 2. My test basically runs with `xvfb-run -a npm run e2e test-8-1.conf.js`. See the yaml:

https://github.com/testing-angular-applications/chapter-8-starter/blob/master/.circleci/config.yml#L19

**Comment by M3ssman** [comment]
Thanks for your efforts! I 'll give it a prompt try and publish the results afterwards, too!

**Comment by M3ssman** [comment]
For anybody that may encounter something similar:
The problem originates from the Sandbox Mode of Google-Chrome itself. So the container has to be run with enhanced capabilities, cf. [https://github.com/jessfraz/dockerfiles/issues/17](https://github.com/jessfraz/dockerfiles/issues/17)
