### ISSUE TITLE
Unable to start or update webdriver-manager, cannot set property 'versionCustom' of undefined

### ISSUE THREAD

**Issue by theAlchemist-dev** [angular/webdriver-manager#259]
Hello,

My system:
- FreeBSD 10.3
- Node.js 7.8.0
- NPM 4.6.1
- webdriver-manager 12.0.6

I am using the following repository: https://github.com/AngularClass/angular-starter.
This repository uses Protractor and that is built on webdriver-manager.

So in the Angular repository are some commands to run webdriver-manager.

Sadly both command fail.
I tried running them manually from the binary but that does not matter.

On start I get the following error:
```
    binaries[binaries_1.Standalone.id].versionCustom = options[Opt.VERSIONS_STANDALONE].getString();
                                                     ^

TypeError: Cannot set property 'versionCustom' of undefined
    at Program.start [as runMethod] (/data/node_root/angular-webpack-starter/node_modules/protractor/node_modules/webdriver-manager/built/lib/cmds/start.js:99:54)
    at Program.run (/data/node_root/angular-webpack-starter/node_modules/protractor/node_modules/webdriver-manager/built/lib/cli/programs.js:61:37)
    at Object.<anonymous> (/data/node_root/angular-webpack-starter/node_modules/protractor/node_modules/webdriver-manager/built/lib/webdriver.js:16:45)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

Using update I receive the same error:
```
    binaries[binaries_1.Standalone.id].versionCustom = options[Opt.VERSIONS_STANDALONE].getString();
                                                     ^

TypeError: Cannot set property 'versionCustom' of undefined
    at Program.update [as runMethod] (/data/node_root/angular-webpack-starter/node_modules/protractor/node_modules/webdriver-manager/built/lib/cmds/update.js:113:54)
    at Program.run (/data/node_root/angular-webpack-starter/node_modules/protractor/node_modules/webdriver-manager/built/lib/cli/programs.js:61:37)
    at Object.<anonymous> (/data/node_root/angular-webpack-starter/node_modules/protractor/node_modules/webdriver-manager/built/lib/webdriver.js:16:45)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

Could you maybe point in the right direction to solve this?

**Comment by cnishina** [comment]
Does this only work in FreeBSD? I am not sure this will work in FreeBSD.

**Comment by theAlchemist-dev** [comment]
@cnishina I only have a FreeBSD server with node.js.
It could definitely be the cause of the problem.

Any idea what I could possible do about this? I don't mind digging in the code if that is necessary

**Comment by cnishina** [comment]
The only problem I have with supporting FreeBSD is that I have no environment to test that FreeBSD works in CI. You could fork the project and add the code you believe is needed OR you could just manually do the steps webdriver-manager does.

Maybe manually would be easier? This is how I'd get it done manually:

```
// get the full ChromeDriver list here: https://chromedriver.storage.googleapis.com
// get the full Standalone list here: https://selenium-release.storage.googleapis.com

// grab the files you need with curl / wget for the OS of interest:
curl -o /path/to/chromedriver_2.31.zip https://chromedriver.storage.googleapis.com/2.31/chromedriver_mac64.zip

curl -o /path/to/selenium-server-standalone-3.5.1.jar https://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.1.jar

// unzip chromedriver...

// start with java
java -Dwebdriver.chrome.driver=/path/to/chromedriver_2.31 -jar /path/to/selenium-server-standalone-3.5.1.jar -port 4444
```

**Comment by cnishina** [comment]
Closing due to staleness. Try the workaround. We are currently not supporting FreeBSD.

**Comment by theAlchemist-dev** [comment]
Oki, thanks for letting me know.
I might try it myself sometimes, but time flies ^^
