### ISSUE TITLE
webdriver-update still cannot work offline, fails in case of DNS error

### ISSUE THREAD

**Issue by attila123** [angular/webdriver-manager#260]
I saw in the changelog that "feat(start): start selenium without making web requests" #232 has been implemented, so I updated webdriver-manager to 12.0.6 in our build system.

We had some DNS problems in our network, and this has proven that unfortunately webdriver-manager still cannot work offline, even though I provide the exact versions of selenium and chrome driver (see below). These selenium and chrome driver versions have been previously installed by webdriver-manager.

webdriver-manager was started as:
```
webdriver-manager start --versions.standalone 3.3.1 --versions.chrome 2.29 --chrome_logs /path/to/chromedriver_7270.log --seleniumPort 7270
```
and now in case of a network failure I got the following error:
```
webdriver-manager: using global installed version 12.0.6
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_AGAIN chromedriver.storage.googleapis.com:443
    at Object.exports._errnoException (util.js:1022:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

Are you aware of this? Is webdriver-manager supposed to work fully offline with #232?
It would be very nice to fix this, please, so webdriver-manager based build systems would not need to depend on Internet access.
(Reproduced under Linux (Centos 7), Node.js version is 6.9.5 if that matters.)

**Comment by trivian118** [comment]
Any updates? using webdriver-manager fails to start behind corporate proxy, every time to start webdriver-manager  I have to run cntlm or fiddler to get around proxy and then  I have to manually update (**webdriver-manager update --proxy http://127.0.0.1:8888)** and then start. Would be great if webdriver-manager start command just started not trying to update

**Comment by attila123** [comment]
Hi @trivian118,
If you do not mind using your corporate proxy every time you start webdriver-manager (with the proxy setting you wrote or with the usual proxy environment variables under Linux), you can stick to concrete selenium, chromedriver, etc. versions (see my example in the problem report), and webdriver-manager will not screw up its cache, and you don't need to update the stuff. Therefore you can decide when to update e.g. chromedriver + chrome and selenium, so you can do the update in a planned way, so it's safer. I think currently that's the best way to do.

**Comment by cnishina** [comment]
Hmmm.... have you ever tried this on a computer that wasn't behind your proxy and disconnecting the internet? How I tested this feature: Turn off wifi and run `webdriver-manager start`. I am pretty sure there are no internet requests being made here...so this is still confusing. Do you have a stacktrace that shows the location in webdriver-manager producing this error other than some event.js? Thanks

**Comment by attila123** [comment]
We had DNS issues again, this time the error message was a bit different:

webdriver-manager: using global installed version 12.0.6
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND chromedriver.storage.googleapis.com chromedriver.storage.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

This gave me an idea to insert the following line to /etc/hosts:
127.0.0.1       chromedriver.storage.googleapis.com

And I started it with `webdriver-manager start --verbose --versions.standalone 3.3.1 --versions.chrome 2.29` which resulted in the following output:
webdriver-manager: using global installed version 12.0.6
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

Still the problem comes from events.js, but at least it can be reproduced with working network and without any proxy setting (on Linux, still with Node.js v6.9.5 (we use it for testing because we suspect that newer versions may not work correctly with jasmine).

**Comment by attila123** [comment]
We did some debugging with a colleague to find the source of net access.
We reached the following function in webdriver-manager/built/lib/binaries/config_source.js:

    requestXml() {
        return new Promise((resolve, reject) => {
            let options = http_utils_1.HttpUtils.initOptions(this.xmlUrl);
            let req = request(options);
            req.on('response', response => {
                if (response.statusCode === 200) {
                    // logger.info('curl -v ' + options.url);
                    let output = '';
                    response.on('data', (data) => {
                        output += data;
                    });
                    response.on('end', () => {
                        resolve(output);
                    });
                }
                else {
                    reject(new Error('response status code is not 200'));
                }
            });
        });
    }
With some logging I determined that in case of error the req.on handler does not get executed.
I placed a `throw new Error('debugging');` to the very beginning of this function to determine the stack trace from where this function gets called, and the result is:

/home/avangel/.nvm/versions/node/v6.9.5/lib/node_modules/webdriver-manager/built/lib/binaries/config_source.js:68
		throw new Error('debugging');
		^

Error: debugging
    at ChromeXml.requestXml (/home/avangel/.nvm/versions/node/v6.9.5/lib/node_modules/webdriver-manager/built/lib/binaries/config_source.js:68:9)
    at ChromeXml.getXml (/home/avangel/.nvm/versions/node/v6.9.5/lib/node_modules/webdriver-manager/built/lib/binaries/config_source.js:39:25)
    at ChromeXml.getVersionList (/home/avangel/.nvm/versions/node/v6.9.5/lib/node_modules/webdriver-manager/built/lib/binaries/chrome_xml.js:22:21)
    at ChromeDriver.getVersionList (/home/avangel/.nvm/versions/node/v6.9.5/lib/node_modules/webdriver-manager/built/lib/binaries/chrome_driver.js:29:38)
    at ChromeDriver.getUrl (/home/avangel/.nvm/versions/node/v6.9.5/lib/node_modules/webdriver-manager/built/lib/binaries/binary.js:52:25)
    at Program.start [as runMethod] (/home/avangel/.nvm/versions/node/v6.9.5/lib/node_modules/webdriver-manager/built/lib/cmds/start.js:134:30)
    at Program.run (/home/avangel/.nvm/versions/node/v6.9.5/lib/node_modules/webdriver-manager/built/lib/cli/programs.js:61:37)
    at Object.<anonymous> (/home/avangel/.nvm/versions/node/v6.9.5/lib/node_modules/webdriver-manager/built/lib/webdriver.js:16:45)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

Hopefully this should help to solve the issue (somehow the code should detect that chromedriver 2.29 is already installed in the system, and should not execute this code, which accesses the Internet).
(I hope that I managed to remove all extra logging I inserted during debugging, and therefore the line numbers are correct.)

**Comment by attila123** [comment]
Yet another example to arbitrary/unnecessary Internet access, now to github (?!?). Fortunately it worked nevertheless.

/home/avangel/.nvm/versions/node/v6.9.5/bin/node /home/avangel/.nvm/versions/node/v6.9.5/bin/webdriver-manager start --versions.standalone 3.3.1 --versions.chrome 2.29
webdriver-manager: using global installed version 12.0.6
Error: Failed to make Github request, rate limit reached.
    at Request.req.on.response (/home/avangel/.nvm/versions/node/v6.9.5/lib/node_modules/webdriver-manager/built/lib/binaries/config_source.js:155:28)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (/home/avangel/.nvm/versions/node/v6.9.5/lib/node_modules/webdriver-manager/node_modules/request/request.js:1074:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)

**Comment by jeffedrington** [comment]
I am also currently running 12.0.6 and experiencing the same issue.  Webdriver-manager runs offline  perfectly when started the first time, but on subsequent runs (after about an hour has passed) it fails with this error:

Error: getaddrinfo ENOTFOUND chromedriver.storage.googleapis.com chromedriver.storage.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

Apparently the webdriver-manager is checking the time stamp of files in the
./protractor/node_modules/webdriver-manager/selenium/* directory, and if they are more than
an hour old it will try to access the internet to update them.  This error can be remedied by running this
command before executing the webdriver-manager:

 touch ./node_modules/protractor/node_modules/webdriver-manager/selenium/*

**Comment by attila123** [comment]
One more fail, now with api.github.com:

`webdriver-manager: using global installed version 12.0.6
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)`

**Comment by praveenkmishra** [comment]
I am trying to execute command webdriver-manager update and I am getting below mention error.
I am on VM where internet connectivity is not available.

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND selenium-release.storage.googleapis.com selenium-release.storage.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

When I run my project in protractor using npm run e2e  I am getting below error
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND chromedriver.storage.googleapis.com chromedriver.storage.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

**Comment by matt-mcc1** [comment]
+1

**Comment by kishorranga** [comment]
**I am also facing the same issue while running Angular2 e2e tests** 

> ng e2e 
webpack: Compiled successfully.
[15:33:36] I/config_source - curl -oc:\test\elastic-alert\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://c
hromedriver.storage.googleapis.com/
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND chromedriver.storage.googleapis.com chromedriver.storage.googleapis.com:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

**Comment by maxbl4** [comment]
Facing the same issue.
I use protractor in Angular, it should download all dependencies from internal corporate repository and it actually does. 
But for unknown reason it performs query to internet address which is blocked on build servers, so e2e tests will never run there

**Comment by erreur404** [comment]
> Facing the same issue.
> I use protractor in Angular, it should download all dependencies from internal corporate repository and it actually does.
> But for unknown reason it performs query to internet address which is blocked on build servers, so e2e tests will never run there

I have exactly the same problem, it works on my computer but doesn't on the build server


    I/config_source - curl -o/[...]/workspace/node_modules/protractor/node_modules/webdriver-        
    manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
    events.js:183
          throw er; // Unhandled 'error' event
          ^

    Error: connect ETIMEDOUT 172.217.21.48:443
        at Object._errnoException (util.js:992:11)
        at _exceptionWithHostPort (util.js:1014:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

**Comment by cnishina** [comment]
I rewrote the whole thing. You can find this in version 13.0.0 and should work now. Start should no longer have any side effects and should work offline. Closing this issue.
