### ISSUE TITLE
Can not run e2e test after webdriver-manager update on Windows

### ISSUE THREAD

**Issue by beginor** [angular/webdriver-manager#285]
I use `@angular/cli:1.5.0` on windows x64, my node version is 8.9.0 , after create a new project with `ng new my-app` , then I run `ng server --open`, which works great!

But when I run `ng e2e`, got error output:

```
webpack: Compiled successfully.
[14:08:25] I/launcher - Running 1 instances of WebDriver
[14:08:25] I/direct - Using ChromeDriver directly...
[14:08:25] E/direct - Error code: 135
[14:08:25] E/direct - Error message: Could not find chromedriver at D:\Projects\
ng-seed\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedr
iver_2.33. Run 'webdriver-manager update' to download binaries.
[14:08:25] E/direct - Error: Could not find chromedriver at D:\Projects\ng-seed\
node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.3
3. Run 'webdriver-manager update' to download binaries.
    at Direct.getNewDriver (D:\Projects\ng-seed\node_modules\protractor\built\dr
iverProviders\direct.js:68:27)
    at Runner.createBrowser (D:\Projects\ng-seed\node_modules\protractor\built\r
unner.js:195:43)
    at q.then.then (D:\Projects\ng-seed\node_modules\protractor\built\runner.js:
339:29)
    at _fulfilled (D:\Projects\ng-seed\node_modules\protractor\node_modules\q\q.
js:834:54)
    at self.promiseDispatch.done (D:\Projects\ng-seed\node_modules\protractor\no
de_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (D:\Projects\ng-seed\node_modules\protrac
tor\node_modules\q\q.js:796:13)
    at D:\Projects\ng-seed\node_modules\protractor\node_modules\q\q.js:556:49
    at runSingle (D:\Projects\ng-seed\node_modules\protractor\node_modules\q\q.j
s:137:13)
    at flush (D:\Projects\ng-seed\node_modules\protractor\node_modules\q\q.js:12
5:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[14:08:25] E/launcher - Process exited with error code 135
npm ERR! code ELIFECYCLE
npm ERR! errno 135
npm ERR! ng-seed@1.0.0 e2e: `ng e2e --webdriver-update false`
npm ERR! Exit status 135
npm ERR!
npm ERR! Failed at the ng-seed@1.0.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     R:\Temp\npm-cache\_logs\2017-11-07T06_08_25_230Z-debug.log
```

**Comment by beginor** [comment]
The error may be caused by `Could not find chromedriver at D:\Projects\ng-seed\
node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.3
3`, I check the directory `node_modules\protractor\node_modules\webdriver-manager\selenium`, the driver file download is

```
 chrome-response.xml
 chromedriver_2.33.exe
 gecko-response.json
 geckodriver-v0.19.1.exe
 selenium-server-standalone-3.7.1.jar
 standalone-response.xml
 update-config.json
```

**Comment by beginor** [comment]
But after I try rename `chromedriver_2.33.exe` to `chromedriver_2.33`, run `ng e2e` again, it works!

```
webpack: Compiled successfully.
[14:14:30] I/launcher - Running 1 instances of WebDriver
[14:14:30] I/direct - Using ChromeDriver directly...

DevTools listening on ws://127.0.0.1:12567/devtools/browser/b743205e-ec50-4c58-b
22f-8034cfb7b26f
Jasmine started

  ng-seed App
    √ should display Navbar Brand

  ng-seed Home
    √ should display a button
    √ should change button text on click

Executed 3 of 3 specs SUCCESS in 11 secs.
[14:14:43] I/launcher - 0 instance(s) of WebDriver still running
[14:14:43] I/launcher - chrome #01 passed
```

I think this should be a bug when find driver file on windows.

**Comment by cnishina** [comment]
I'll try this out later. If this is how it is currently working, this is broken and I'll have a fix / release.

**Comment by cnishina** [comment]
Alright I was unable to get this to reproduce on Windows. It downloads the .exe file and the update-config.json has the right version / file type.

**Comment by beginor** [comment]
@cnishina Yes, it can download the exe file, which is `chromedriver_2.33.exe` now, but when I type `ng e2e` to run e2e test , it will try to use the `chromedriver_2.33` instead of `chromedriver_2.33.exe`, so `ng e2e` will fail on windows. 

But if I rename `chromedriver_2.33.exe` to `chromedriver_2.33` , `ng e2e` runs success on windows.

**Comment by cnishina** [comment]
Have you tried this without the angular-cli? Have you tried with just Protractor? I'm trying to understand if this is a Protractor problem, an angular-cli problem, or something else. Protractor should read the update-config.json and if you are saying that the exe version is downloaded, then Protractor should launch chromedriver with direct connect. 

Also, read your update-config.json and check to see what the "last" version is.
