### ISSUE TITLE
webdriver-manager lacks support for JAVA_HOME

### ISSUE THREAD

**Issue by nanobot248** [angular/webdriver-manager#293]
I have multiple JVMs installed on my system. Most java-base software and tools support switching between JVMs/JDKs by using the JAVA_HOME variable.
webdriver-manager doesn't support this and just calls the "java" command, so at the moment i have to manually patch my webdriver-manager/built/lib/cmds/start.js file.

Environment/steps to reproduce:

1. Ubuntu 16.04
2. default JDK/JRE 1.7, JAVA_HOME points to java 1.8 JDK
3. install protractor globally (`sudo npm install -g protractor`).
4. `webdriver-manager update` (webdriver-version is 12.0.6. now)
5. `webdriver-manager start`:
```
[19:37:45] I/start - java  -Djava.security.egd=file:///dev/./urandom -Dwebdriver.chrome.driver=/usr/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.34 -Dwebdriver.gecko.driver=/usr/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.19.1 -jar /usr/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.8.1.jar -port 4444
[19:37:45] I/start - seleniumProcess.pid: 3649
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openqa/grid/selenium/GridLauncherV3 : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
[19:37:45] I/start - Selenium Standalone has exited with code 1
```

There is already at least one issue on [stackoverflow](https://stackoverflow.com/questions/34462283/cant-start-webdriver-manager-after-upgrading-of-jdk-node-webdriver) about this. After adding process.env.JAVA_HOME support, it worked perfectly.

Any chances this could be added to webdriver-manager?

**Comment by cnishina** [comment]
JAVA_HOME is now supported with 13.
