### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by jgentes** [angular/webdriver-manager#302]
I'm seeing this on CircleCI while using the latest version (5.3.0) of protractor and node v9.3.0:

```
$ webdriver-manager update

/home/ubuntu/startupcommunity/node_modules/protractor/node_modules/webdriver-manager/built/lib/webdriver.js:3
const minimist = require("minimist");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/startupcommunity/node_modules/protractor/bin/webdriver-manager:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

webdriver-manager update returned exit code 8

Action failed: webdriver-manager update
```

Should I raise an issue with protractor?

**Comment by cnishina** [comment]
There was no additional response so it is difficult to debug. Closing this issue as obsolete.
