### ISSUE TITLE
Fails to install Linux for ChromeDriver version 2.37

### ISSUE THREAD

**Issue by alexQueue** [angular/webdriver-manager#305]
It seems to just be mysteriously missing from only this version.

Failing case (2.37)
```bash
$ webdriver-manager --versions.chrome=2.37 update
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open '/webdriver-manager/selenium/chromedriver_2.37linux64.zip'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at Function.FileManager.toDownload (/webdriver-manager/built/lib/files/file_manager.js:174:35)
    at updateBinary (/webdriver-manager/built/lib/cmds/update.js:167:32)
    at Program.update [as runMethod] (/webdriver-manager/built/lib/cmds/update.js:125:9)
    at Program.run (/webdriver-manager/built/lib/cli/programs.js:60:14)
    at Object.<anonymous> (/webdriver-manager/built/lib/webdriver.js:15:45)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
```

Working case using a previous version:
```bash
$ webdriver-manager --versions.chrome=2.36 update
[18:21:47] I/downloader - selenium standalone: downloading version 2.53.1
[18:21:47] I/downloader - curl -o /webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
[18:21:47] I/update - geckodriver: file exists /webdriver-manager/selenium/geckodriver-v0.11.1-linux64.tar.gz
[18:21:47] I/update - geckodriver: unzipping geckodriver-v0.11.1-linux64.tar.gz
[18:21:47] I/update - geckodriver: setting permissions to 0755 for /webdriver-manager/selenium/geckodriver-v0.11.1
[18:21:47] I/update - geckodriver: vv0.11.1 up to date
[18:21:47] I/update - chromedriver: file exists /webdriver-manager/selenium/chromedriver_2.36linux64.zip
[18:21:47] I/update - chromedriver: unzipping chromedriver_2.36linux64.zip
[18:21:48] I/update - chromedriver: setting permissions to 0755 for /webdriver-manager/selenium/chromedriver_2.36
[18:21:48] I/update - chromedriver: v2.36 up to date
```

This is only reproducible on my Linux box, since my Mac downloads the Mac version without issue.

Working on my Mac:
```bash
$ webdriver-manager --versions.chrome=2.37 update
[14:35:56] I/downloader - selenium standalone: downloading version 2.53.1
[14:35:56] I/downloader - curl -o /webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
[14:35:56] I/downloader - chromedriver: downloading version 2.37
[14:35:56] I/downloader - curl -o /webdriver-manager/selenium/chromedriver_2.37mac64.zip https://chromedriver.storage.googleapis.com/2.37/chromedriver_mac64.zip
[14:35:56] I/downloader - geckodriver: downloading version v0.11.1
[14:35:56] I/downloader - curl -o /webdriver-manager/selenium/geckodriver-v0.11.1-macos.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-macos.tar.gz
[14:35:56] I/update - chromedriver: unzipping /webdriver-manager/selenium/chromedriver_2.37mac64.zip
[14:35:57] I/update - chromedriver: setting permissions to 0755 for /webdriver-manager/selenium/chromedriver_2.37
[14:35:57] I/update - geckodriver: unzipping /webdriver-manager/selenium/geckodriver-v0.11.1-macos.tar.gz
[14:35:57] I/update - geckodriver: setting permissions to 0755 for /webdriver-manager/selenium/geckodriver-v0.11.1
```

**Comment by cnishina** [comment]
Please try this again with the latest. I am going to close this because I don't think this is an issue anymore.
