### ISSUE TITLE
Not able to use Eclipse for Protractor

### ISSUE THREAD

**Issue by vikramchenna** [angular/webdriver-manager#309]
Hi,
I configured eclipse for protractor. While I am running the script, got below error and unable to solve it. Can anybody help please. 

\node_modules\protractor\built\logger.js:79
    info(...msgs) {
         ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (E:\ProtractorScripts\Unocareer\node_modules\protractor\built\configParser.js:6:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by macroking** [comment]
This does not belong here. Please close this and create a question in SO. BTW, I guess this issue is due to incompatible diver and browser version.

**Comment by cnishina** [comment]
This is an issue with the node version you are using. You will need to set the node version for Eclipse.  Since this is an environment set up, I am closing this issue.
