### ISSUE TITLE
webdriver manager cannot find chalk

### ISSUE THREAD

**Issue by cnishina** [angular/webdriver-manager#31]
webdriver manager cannot find chalk
```
node node_modules/webdriver-manager/bin/webdriver-manager update
module.js:440
    throw err;
    ^

Error: Cannot find module '/Users/cnishina/src/temp/node_modules/chalk/node_modules/webdriver-manager/bin/webdriver-manager'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
```

**Comment by cnishina** [comment]
appears to be resolved with 0cfcc88f1383c400f72ea5e49f9600ff652f8214.
