### ISSUE TITLE
webdriver-manager update fails

### ISSUE THREAD

**Issue by klinki** [angular/webdriver-manager#311]
Hello, 
I have a problem with `webdriver-manager update` command.

It fails with following error:
```
[20:21:28] I/file_manager - creating folder /opt/atlassian/pipelines/agent/build/node_modules/webdriver-manager/selenium
[20:21:29] I/update - chromedriver: unzipping chromedriver_2.39.zip
[20:21:29] I/update - chromedriver: setting permissions to 0755 for /opt/atlassian/pipelines/agent/build/node_modules/webdriver-manager/selenium/chromedriver_2.39
[20:21:29] I/update - geckodriver: unzipping geckodriver-v0.20.1.tar.gz
[20:21:29] I/update - geckodriver: setting permissions to 0755 for /opt/atlassian/pipelines/agent/build/node_modules/webdriver-manager/selenium/geckodriver-v0.20.1
(node:415) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[20:21:30] I/launcher - Running 1 instances of WebDriver
[20:21:30] I/direct - Using ChromeDriver directly...
[20:21:30] E/launcher - spawn /opt/atlassian/pipelines/agent/build/node_modules/webdriver-manager/selenium/chromedriver_2.39 ENOENT
[20:21:30] E/launcher - Error: spawn /opt/atlassian/pipelines/agent/build/node_modules/webdriver-manager/selenium/chromedriver_2.39 ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[20:21:30] E/launcher - Process exited with error code 199
```

**Comment by cnishina** [comment]
Please try the latest version. Closing this issue as part of new codebase
