### ISSUE TITLE
EHOSTUNREACH when starting webdriver-manager

### ISSUE THREAD

**Issue by catastrophe-brandon** [angular/webdriver-manager#317]
When I try to start webdriver-manager I am encountering EHOSTUNREACH (see the output below). I am starting a server, so I wasn't expecting the server to try to reach out and contact another machine. I don't have great visibility into the internals of Protractor; could someone more familiar explain what is happening here and what the best way to remedy the situation would be?
 
```
$ webdriver-manager start
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: tunneling socket could not be established, cause=connect EHOSTUNREACH <REDACTED>:80 - Local (<REDACTED>:50082)
    at ClientRequest.onError (/usr/local/lib/node_modules/protractor/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:382:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Request.onRequestError (/usr/local/lib/node_modules/protractor/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.onError (/usr/local/lib/node_modules/protractor/node_modules/tunnel-agent/index.js:179:21)
    at Object.onceWrapper (events.js:273:13)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by catastrophe-brandon** [comment]
After updating webdriver-manager and tweaking some proxy settings the issue seems to have gone away. Unfortunately I'm not sure which exact setting corrected the issue for me. After updating I am using webdriver-manager 12.0.6. I guess the most valuable thing to know if you encounter this error is it's possible that your proxy settings may be incorrect.
