### ISSUE TITLE
webdriver-manager update command getting issue 

### ISSUE THREAD

**Issue by rushi29592** [angular/webdriver-manager#321]
C:\windows\system32>webdriver-manager update
webdriver-manager: using global installed version 12.1.0
[17:41:53] I/config_source - curl -oC:\Users\rushikeshp2\AppData\Roaming\npm\node_modules\webdriver-manager\selenium\standalone-response.xml https://selenium-release.storage.googleapis.com/
[17:41:53] I/config_source - curl -oC:\Users\rushikeshp2\AppData\Roaming\npm\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
[17:41:53] I/config_source - curl -oC:\Users\rushikeshp2\AppData\Roaming\npm\node_modules\webdriver-manager\selenium\gecko-response.json https://api.github.com/repos/mozilla/geckodriver/releases
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TLSWrap.onread (net.js:618:25)

C:\windows\system32>

**Comment by rushi29592** [comment]
any update

**Comment by cnishina** [comment]
Closing this issue. If this is still an issue, please let me know.
