### ISSUE TITLE
update failing with ignore_ssl in Node 8.12.0

### ISSUE THREAD

**Issue by bensgroi** [angular/webdriver-manager#326]
Since updating to Node 8.12.0 / npm 6.4.1, `webdriver-manager update --ignore_ssl` has been failing for us:
``` sh
[11:03:04] I/file_manager - creating folder ...\hpc-breadcrumb\node_modules\protractor\node_modules\webdriver-manager\selenium
[11:03:04] I/http_utils - ignoring SSL certificate
[11:03:04] I/config_source - curl -ok ...\hpc-breadcrumb\node_modules\protractor\node_modules\webdriver-manager\selenium\standalone-response.xml https://selenium-release.storage.googleapis.com/
[11:03:04] I/http_utils - ignoring SSL certificate
[11:03:04] I/config_source - curl -ok ...\hpc-breadcrumb\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
[11:03:04] I/http_utils - ignoring SSL certificate
[11:03:04] I/http_utils - ignoring SSL certificate
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onread (net.js:622:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hpc-breadcrumb@3.0.5 update-webdriver: `webdriver-manager update --ignore_ssl --gecko false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hpc-breadcrumb@3.0.5 update-webdriver script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ...\AppData\Roaming\npm-cache\_logs\2018-10-16T15_03_04_629Z-debug.log
```

**Comment by vort3xxx** [comment]
If I use --alternate_cdn with a non-https url, it works.  All https-based cdns fail with node 8.12.

**Comment by cnishina** [comment]
Alternative cdn does not work...I responded to your previous comment. Discussion: https://github.com/angular/webdriver-manager/issues/325

Question about ignore SSL. What is the environment setup that requires this?

**Comment by bensgroi** [comment]
@cnishina My employer injects a self-signed cert into the certificate chain, unfortunately. We've reported to IT that it breaks numerous development operations, but we haven't gotten anywhere. So we're forced to use the `ignore_ssl` flag. It worked fine until 8.12.0.

@vort3xxx Where did you hear about the node 8.12 + https CDN issue?

**Comment by bensgroi** [comment]
Update on this: I realized that we only need `ignore_ssl` on our developer machines. Our cloud build happen Hosted VS2017 images in Azure DevOps. I removed the `ignore_ssl` flag and re-ran in Azure and I'm still getting the error, so it seems like `ignore_ssl` is not part of the equation.

``` sh
2018-10-16T21:50:53.6081698Z ; node bin location = C:\Program Files\nodejs\node.exe
2018-10-16T21:50:53.6081807Z ; cwd = D:\a\1\s
2018-10-16T21:50:53.6081931Z ; HOME = C:\Users\VssAdministrator
2018-10-16T21:50:53.6082062Z ; "npm config ls -l" to show all defaults.
2018-10-16T21:50:53.6082154Z 
2018-10-16T21:50:53.6083050Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" run update-webdriver"
2018-10-16T21:50:55.2961769Z events.js:183
2018-10-16T21:50:55.2962041Z       throw er; // Unhandled 'error' event
2018-10-16T21:50:55.2962094Z       ^
2018-10-16T21:50:55.2962125Z 
2018-10-16T21:50:55.2962171Z Error: read ECONNRESET
2018-10-16T21:50:55.2962234Z     at TLSWrap.onread (net.js:622:25)
2018-10-16T21:50:55.2962279Z npm ERR! code ELIFECYCLE
2018-10-16T21:50:55.2962358Z npm ERR! errno 1
2018-10-16T21:50:55.2962408Z npm ERR! hpc-breadcrumb@3.0.6 update-webdriver: `webdriver-manager update --gecko false`
2018-10-16T21:50:55.2962470Z npm ERR! Exit status 1
2018-10-16T21:50:55.2962514Z npm ERR! 
2018-10-16T21:50:55.2962561Z npm ERR! Failed at the hpc-breadcrumb@3.0.6 update-webdriver script.
2018-10-16T21:50:55.2962612Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-10-16T21:50:55.2962674Z 
2018-10-16T21:50:55.2962720Z npm ERR! A complete log of this run can be found in:
2018-10-16T21:50:55.2962769Z npm ERR!     C:\npm\cache\_logs\2018-10-16T21_50_55_262Z-debug.log
2018-10-16T21:50:55.2962800Z 
2018-10-16T21:50:55.2962860Z > hpc-breadcrumb@3.0.6 update-webdriver D:\a\1\s
2018-10-16T21:50:55.2962908Z > webdriver-manager update --gecko false
2018-10-16T21:50:55.2962937Z 
2018-10-16T21:50:55.2962987Z [21:50:54] I/file_manager - creating folder D:\a\1\s\node_modules\protractor\node_modules\webdriver-manager\selenium
2018-10-16T21:50:55.2964645Z [21:50:54] I/config_source - curl -oD:\a\1\s\node_modules\protractor\node_modules\webdriver-manager\selenium\standalone-response.xml https://selenium-release.storage.googleapis.com/
2018-10-16T21:50:55.2964691Z [21:50:54] I/config_source - curl -oD:\a\1\s\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
2018-10-16T21:50:55.3652756Z Found npm debug log, make sure the path matches with the one in npm's output: C:\npm\cache\_logs\2018-10-16T21_50_55_262Z-debug.log
2018-10-16T21:50:55.3652889Z 0 info it worked if it ends with ok
2018-10-16T21:50:55.3652970Z 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
2018-10-16T21:50:55.3653021Z 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
2018-10-16T21:50:55.3653078Z 1 verbose cli   'run',
2018-10-16T21:50:55.3653124Z 1 verbose cli   'update-webdriver' ]
2018-10-16T21:50:55.3653196Z 2 info using npm@6.4.1
2018-10-16T21:50:55.3653283Z 3 info using node@v8.12.0
2018-10-16T21:50:55.3653329Z 4 verbose run-script [ 'preupdate-webdriver',
2018-10-16T21:50:55.3653404Z 4 verbose run-script   'update-webdriver',
2018-10-16T21:50:55.3653451Z 4 verbose run-script   'postupdate-webdriver' ]
2018-10-16T21:50:55.3653499Z 5 info lifecycle hpc-breadcrumb@3.0.6~preupdate-webdriver: hpc-breadcrumb@3.0.6
2018-10-16T21:50:55.3653726Z 6 info lifecycle hpc-breadcrumb@3.0.6~update-webdriver: hpc-breadcrumb@3.0.6
2018-10-16T21:50:55.3653787Z 7 verbose lifecycle hpc-breadcrumb@3.0.6~update-webdriver: unsafe-perm in lifecycle true
2018-10-16T21:50:55.3653983Z 8 verbose lifecycle hpc-breadcrumb@3.0.6~update-webdriver: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\a\1\s\node_modules\.bin;C:\agents\2.140.2\externals\git\cmd;C:\tools\mingw64\bin;C:\Program Files\dotnet;C:\mysql-5.7.21-winx64\bin;C:\Program Files\Java\jdk1.8.0_181\bin;C:\npm\prefix;C:\hostedtoolcache\windows\Ruby\2.5.0\x64\bin;C:\Go1.11\bin;C:\Program Files\Git\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Scripts;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64;C:\Program Files\Microsoft MPI\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\Chocolatey\bin;C:\Program Files\Docker;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\Git\cmd;C:\Program Files (x86)\Subversion\bin;C:\Program Files\nodejs\;C:\Program Files\CMake\bin;C:\Users\VssAdministrator\AppData\Local\Microsoft\WindowsApps
2018-10-16T21:50:55.3654173Z 9 verbose lifecycle hpc-breadcrumb@3.0.6~update-webdriver: CWD: D:\a\1\s
2018-10-16T21:50:55.3654218Z 10 silly lifecycle hpc-breadcrumb@3.0.6~update-webdriver: Args: [ '/d /s /c', 'webdriver-manager update --gecko false' ]
2018-10-16T21:50:55.3654269Z 11 silly lifecycle hpc-breadcrumb@3.0.6~update-webdriver: Returned: code: 1  signal: null
2018-10-16T21:50:55.3654334Z 12 info lifecycle hpc-breadcrumb@3.0.6~update-webdriver: Failed to exec update-webdriver script
2018-10-16T21:50:55.3654374Z 13 verbose stack Error: hpc-breadcrumb@3.0.6 update-webdriver: `webdriver-manager update --gecko false`
2018-10-16T21:50:55.3654412Z 13 verbose stack Exit status 1
2018-10-16T21:50:55.3654476Z 13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
2018-10-16T21:50:55.3654515Z 13 verbose stack     at emitTwo (events.js:126:13)
2018-10-16T21:50:55.3655112Z 13 verbose stack     at EventEmitter.emit (events.js:214:7)
2018-10-16T21:50:55.3655182Z 13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
2018-10-16T21:50:55.3655221Z 13 verbose stack     at emitTwo (events.js:126:13)
2018-10-16T21:50:55.3655343Z 13 verbose stack     at ChildProcess.emit (events.js:214:7)
2018-10-16T21:50:55.3655405Z 13 verbose stack     at maybeClose (internal/child_process.js:915:16)
2018-10-16T21:50:55.3655446Z 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2018-10-16T21:50:55.3655483Z 14 verbose pkgid hpc-breadcrumb@3.0.6
2018-10-16T21:50:55.3655518Z 15 verbose cwd D:\a\1\s
2018-10-16T21:50:55.3655579Z 16 verbose Windows_NT 10.0.14393
2018-10-16T21:50:55.3655620Z 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "update-webdriver"
2018-10-16T21:50:55.3655664Z 18 verbose node v8.12.0
2018-10-16T21:50:55.3655724Z 19 verbose npm  v6.4.1
2018-10-16T21:50:55.3655759Z 20 error code ELIFECYCLE
2018-10-16T21:50:55.3655793Z 21 error errno 1
2018-10-16T21:50:55.3655832Z 22 error hpc-breadcrumb@3.0.6 update-webdriver: `webdriver-manager update --gecko false`
2018-10-16T21:50:55.3655891Z 22 error Exit status 1
2018-10-16T21:50:55.3655935Z 23 error Failed at the hpc-breadcrumb@3.0.6 update-webdriver script.
2018-10-16T21:50:55.3655974Z 23 error This is probably not a problem with npm. There is likely additional logging output above.
2018-10-16T21:50:55.3656035Z 24 verbose exit [ 1, true ]
2018-10-16T21:50:55.3656061Z 
2018-10-16T21:50:55.3712347Z ##[error]Error: Npm failed with return code: 1
2018-10-16T21:50:55.3847904Z ##[section]Finishing: update webdriver
```

**Comment by vort3xxx** [comment]
The alternate_cdn thing seems to have been red herring / intermittent reproducability issue for me.  It must have "worked by accident" when I had that setting enabled.  I don't think my reproduction steps were solid at that point in time and my confidence has diminished that I actually know what's the root cause with this error.  At the time, I was trying to find a way to shut off https to ascertain if it was near the root. 

When I was looking at this yesterday, it seemed like it failed on the first attempt at running, and any subsequent run would succeed.   In order to reproduce, I was deleting node_modules, and re-running `npm install` before running `webdriver-manager update`.   Today, that reproduction step is only working intermittently on my local dev machine.

**Comment by vort3xxx** [comment]
Interestingly, if I use the webdriver-manager-replacement project hosted on npm, it downloads every time, however it's not a child of the `protractor` package, so it's pretty useless for my use case.

**Comment by bensgroi** [comment]
Same here -- the command works reliably the second time. Reproducing involves clearing out node_modules first. So naturally, it affects CI environments consistently.

**Comment by cnishina** [comment]
@vort3xxx So for the current failures, I imagine there was some promise that was not being waited upon.

The for the part where it is not a dependency of Protractor... I'll keep you posted.

**Comment by bensgroi** [comment]
@cnishina re the issue renaming -- as I noted above, it doesn't actually seem to have anything to do with `ignore_ssl`, since I get the error regardless of whether I use that flag. Node 8.12.0 seems to be the determining factor.

**Comment by markleppke** [comment]
I can confirm if I roll back to Node 8.11.4 it works for me. Unfortunately, our team needs move to 8.12.0.

**Comment by markleppke** [comment]
This may be related: https://github.com/nodejs/node/issues/23237

**Comment by jeroenheijmans** [comment]
FWIW with #329 I probably created a duplicate issue. My first post there contains steps for a minimal repro. (Though it might indeed well be a Node 8.12 issue...)

**Comment by cnishina** [comment]
I have updated ignore ssl in webdriver-manager 13 (note that it does not work with Protractor 5.4.2 with driver providers: direct connect or local). We can now do a post review (be nice) of the new code I wrote using the request node module.

I try to get the options set for the ssl here:
https://github.com/angular/webdriver-manager/blob/master/lib/provider/utils/http_utils.ts#L56

This calls:
https://github.com/angular/webdriver-manager/blob/master/lib/provider/utils/http_utils.ts#L71

Is everyone still stuck on node 8? I'm using node 10 now...

**Comment by cnishina** [comment]
Maybe I could have an ignore_ssl test and add it to https://github.com/angular/webdriver-manager/blob/master/lib/provider/utils/http_utils.spec-int.ts

I would also be okay having someone telling me it works.
