### ISSUE TITLE
Webdriver manager is not getting updated 

### ISSUE THREAD

**Issue by 86SUSHIL** [angular/webdriver-manager#427]
Can you please help me to resolve below issue to run in remote via jenkins pipeline
package.json
"scripts": {
"preupdate-webdriver": "npm install",
"update-webdriver": "webdriver-manager update --proxy http://xx.xxx.xxx.xx:xxxx --ignore_ssl --gecko false --versions.chrome 2.46",
"preprotractor": "npm run update-webdriver",
"protractor": "protractor conf.js"
},

Config.js
// directConnect: true,
seleniumAddress: 'http://localhost:4444/wd/hub/',
framework: "jasmine2",

Error:
npm run protractor
preprotractor /apps/jenkins/build/

npm run update-webdriver

preupdate-webdriver /apps/jenkins/build/

npm install

npm WARN grunt-protractor-runner@5.0.0 requires a peer of grunt@>=0.4.0 but none was installed.

up to date in 3.659s

1588242@1.0.0 update-webdriver /apps/jenkins/build/workspace/CDUD/quickstartmaster_protractor/master/SNAPSHOT
webdriver-manager update --proxy http://xx.xxx.xxx.xx:xxxx--ignore_ssl --gecko false --versions.chrome 2.46

[12:48:25] I/http_utils - ignoring SSL certificate
[12:48:25] I/config_source - curl -ok /apps/jenkins/build/node_modules/protractor/node_modules/webdriver-manager/selenium/standalone-response.xml 'http://xx.xxx.xxx.xx:xxxx' -H 'host:selenium-release.storage.googleapis.com'
[12:48:25] I/http_utils - ignoring SSL certificate
[12:48:25] I/config_source - curl -ok /apps/jenkins/build/node_modules/protractor/node_modules/webdriver-manager/selenium/chrome-response.xml 'http://xx.xxx.xxx.xx:xxxx' -H 'host:chromedriver.storage.googleapis.com'
(node:1716) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: response status code is not 200
(node:1716) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1716) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: response status code is not 200

protractor /apps/jenkins/build
protractor conf.js

[12:48:27] I/launcher - Running 1 instances of WebDriver
[12:48:27] I/hosted - Using the selenium server at http://localhost:4444/wd/hub/
[12:48:27] E/launcher - Error code: 135
[12:48:27] E/launcher - Error message: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
[12:48:27] E/launcher - Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
at ClientRequest. (/apps/jenkins/build/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:238:15)
at emitOne (events.js:115:13)
at ClientRequest.emit (events.js:210:7)
at Socket.socketErrorListener (_http_client.js:401:9)
at emitOne (events.js:115:13)
at Socket.emit (events.js:210:7)
at emitErrorNT (internal/streams/destroy.js:64:8)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
From: Task: WebDriver.createSession()
at Function.createSession (/apps/jenkins/build/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
at Function.createSession (/apps/jenkins/build/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:761:15)
at createDriver (/apps/jenkins/build/node_modules/protractor/node_modules/selenium-webdriver/index.js:170:33)
at Builder.build (/apps/jenkins/build/node_modules/protractor/node_modules/selenium-webdriver/index.js:626:16)
at Hosted.getNewDriver (/apps/jenkins/build/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
at Runner.createBrowser (/apps/jenkins/build/node_modules/protractor/built/runner.js:195:43)
at q.then.then (/apps/jenkins/build/node_modules/protractor/built/runner.js:339:29)
at _fulfilled (/apps/jenkins/build/node_modules/q/q.js:834:54)
at self.promiseDispatch.done (/apps/jenkins/build/node_modules/q/q.js:863:30)
at Promise.promise.promiseDispatch (/apps/jenkins/build/node_modules/q/q.js:796:13)
[12:48:27] E/launcher - Process exited with error code 135
npm ERR! code ELIFECYCLE
npm ERR! errno 135
npm ERR! 1588242@1.0.0 protractor: protractor conf.js
npm ERR! Exit status 135
npm ERR!
npm ERR! Failed at the protractor script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /apps/jenkins/build/npm-cache/_logs/2019-09-27T12_48_27_623Z-debug.log

**Comment by Lucas-C** [comment]
```
 (node:1716) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: response status code is not 200
```

The HTTP proxy you specified probably does not allow the request to `selenium-release.storage.googleapis.com` to pass through
