### ISSUE TITLE
WebDriverError: unknown error: Chrome failed to start: exited abnormally.

### ISSUE THREAD

**Issue by Mumcio** [angular/webdriver-manager#444]
Hi all,

I am trying to run e2e tests (angular + protractor).
It worked fine with since chrome 80.

Docker images:
https://hub.docker.com/r/intelerad/bitbucket-pipelines-protractor/
https://hub.docker.com/r/trion/ng-cli-e2e/
I checked:
- webdriver manager update in node_modules
- downgrading protractor & reinstall
- adding chromeOptions in protractor config like "--no-sandbox"

Any idea how to resolve it ?

I am getting such error after trying to run tests

`｢wdm｣: Compiled successfully.
[07:29:05] I/downloader - curl -o/app/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_80.0.3987.16.zip https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_linux64.zip
[07:29:05] I/downloader - curl -o/app/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_80.0.3987.16.zip https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_linux64.zip
[07:29:06] I/update - chromedriver: unzipping chromedriver_80.0.3987.16.zip
[07:29:07] I/update - chromedriver: setting permissions to 0755 for /app/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_80.0.3987.16
[07:29:07] I/update - chromedriver: unzipping chromedriver_80.0.3987.16.zip
[07:29:07] I/update - chromedriver: setting permissions to 0755 for /app/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_80.0.3987.16
[07:29:09] I/launcher - Running 1 instances of WebDriver
[07:29:09] I/direct - Using ChromeDriver directly...

/app/node_modules/selenium-webdriver/lib/error.js:546
        throw new ctor(message);
              ^
WebDriverError: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}),platform=Linux 4.19.76-linuxkit x86_64)
    at Object.checkLegacyResponse (/app/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/app/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/app/node_modules/selenium-webdriver/lib/http.js:441:30)
    at ZoneDelegate.invoke (/app/node_modules/zone.js/dist/zone-node.js:391:26)
    at Zone.run (/app/node_modules/zone.js/dist/zone-node.js:150:43)
    at /app/node_modules/zone.js/dist/zone-node.js:889:34
    at ZoneDelegate.invokeTask (/app/node_modules/zone.js/dist/zone-node.js:423:31)
    at Zone.runTask (/app/node_modules/zone.js/dist/zone-node.js:195:47)
    at drainMicroTaskQueue (/app/node_modules/zone.js/dist/zone-node.js:601:35)
    at ZoneTask.invokeTask (/app/node_modules/zone.js/dist/zone-node.js:502:21)
From: Task: WebDriver.createSession()
    at Function.createSession (/app/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/app/node_modules/selenium-webdriver/chrome.js:761:15)
    at Direct.getNewDriver (/app/node_modules/protractor/built/driverProviders/direct.js:77:33)
    at Runner.createBrowser (/app/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/app/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/app/node_modules/q/q.js:834:54)
    at /app/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:796:13)
    at /app/node_modules/q/q.js:556:49
    at runSingle (/app/node_modules/q/q.js:137:13)
[07:29:10] E/launcher - Process exited with error code 1
An unexpected error occurred: undefined`

**Comment by Mumcio** [comment]
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3336
