### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by aliriomiguel** [angular/webdriver-manager#449]
So i've been having this error everytime i want to start my e2e testing using angular protractor-cucumber-framework

`$ ng e2e
[09:22:21] I/config_source - curl -oC:\Cucumber-Protractor-Framework\e2e-testing\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1475:34)
    at TLSSocket.emit (events.js:321:20)
    at TLSSocket._finishInit (_tls_wrap.js:918:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:688:12)
Emitted 'error' event on Request instance at:
    at Request.onRequestError (C:\Cucumber-Protractor-Framework\e2e-testing\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:333:22)
    at TLSSocket.socketErrorListener (_http_client.js:424:9)
    at TLSSocket.emit (events.js:321:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}`

i checked the urls and i can see what is in https://chromedriver.storage.googleapis.com/ 

Any ideas, tutorials or other issues related to this error?

BTW: Yes, if i use th command 

ng e2e --webdriver-update=false

it works, but the thing is that it was working without the attribute before.

**Comment by PirogovClub** [comment]
Same here, issue with webdriver update

```
I/config_source - curl -oXXX\node_modules\protractor\node_modules\webdriver-manager\selenium\iedriver-response.xml https://selenium-release.storage.googleapis.com/
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
Emitted 'error' event on Request instance at:
    at Request.onRequestError (XXX\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:228:7)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

and this works before
