### ISSUE TITLE
webdriver-manager does not work with selenium webdriver 4.0.0

### ISSUE THREAD

**Issue by dvasconcelos1** [angular/webdriver-manager#463]
Browser: Firefox
selenium-webdriver: 4.0.0-alpha.7
webdriver-manager: 12.1.7

```
Error: The geckodriver executable could not be found on the current PATH. Please download the latest version from https://github.com/mozilla/geckodriver/releases/ and ensure it can be found on your PATH.
    at findGeckoDriver (node_modules/selenium-webdriver/firefox.js:445:11)
    at new ServiceBuilder (node_modules/selenium-webdriver/firefox.js:534:22)
```

**Comment by dvasconcelos1** [comment]
Sorry, It might have been some misconfiguration. Changing the url to HTTPS instead of HTTP seems to work.
