### ISSUE TITLE
After latest webdriver-manager update it no longer starts

### ISSUE THREAD

**Issue by Halt001** [angular/webdriver-manager#485]
After running the web driver-manager update it no longer works. This is the error:

[13:45:11] I/launcher - Running 1 instances of WebDriver
[13:45:11] I/direct - Using ChromeDriver directly...
[13:45:11] E/runner - Unable to start a WebDriver session.
[13:45:11] E/launcher - Error: Error: spawn Unknown system error -86
    at ChildProcess.spawn (internal/child_process.js:406:11)
    at Object.spawn (child_process.js:548:9)
    
I have updated Chrome to the latest version but that didn't help.

I'm on MacOS 11.1

**Comment by Halt001** [comment]
Found the problem. It was related to this issue: `https://github.com/angular/webdriver-manager/issues/476`
