### ISSUE TITLE
Unhandled promise rejection when trying to install non-existent browser version

### ISSUE THREAD

**Issue by thw0rted** [angular/webdriver-manager#487]
This is a different issue from #393, in spite of the similar title.  The resolution for that issue was to check that a full semver was passed as an argument, but I'm talking about user error where a Chrome version is specified that isn't present in the index (XML) downloaded from the server.

Try running `webdriver-manager update --versions.chrome=88.77.66.55` (or any a non-existent version).  You'll wind up with output like

````text
[12:37:38] E/downloader - options.uri is a required argument
[12:37:38] I/update - chromedriver: file exists ...\node_modules\webdriver-manager\selenium\chromedriver_88.77.66.55.zip
[12:37:38] I/update - chromedriver: unzipping chromedriver_88.77.66.55.zip
(node:19840) UnhandledPromiseRejectionWarning: Error: Invalid filename: ...\node_modules\webdriver-manager\selenium\chromedriver_88.77.66.55.zip
    at unzip (...\node_modules\webdriver-manager\built\lib\cmds\update.js:232:19)
    at ...\node_modules\webdriver-manager\built\lib\cmds\update.js:205:13
    at async Promise.all (index 1)
(node:19840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

Failure to handle this error also means that the script's exit code is zero, so it's impossible to use `webdriver-manager update` in a script and fail gracefully when it doesn't actually install the chromedriver.

**Comment by kwisatz** [comment]
```
~$ webdriver-manager update --versions.chrome=$(chromium --version | cut -d ' ' -f 2)
webdriver-manager: using global installed version 12.1.9
[14:49:41] I/config_source - curl -o/home/kwisatz/.nvm/versions/node/v18.16.0/lib/node_modules/webdriver-manager/selenium/standalone-response.xml https://selenium-release.storage.googleapis.com/
[14:49:41] I/config_source - curl -o/home/kwisatz/.nvm/versions/node/v18.16.0/lib/node_modules/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
[14:49:41] I/config_source - curl -o/home/kwisatz/.nvm/versions/node/v18.16.0/lib/node_modules/webdriver-manager/selenium/gecko-response.json https://api.github.com/repos/mozilla/geckodriver/releases
[14:49:41] E/downloader - options.uri is a required argument
[14:49:41] I/update - chromedriver: file exists /home/kwisatz/.nvm/versions/node/v18.16.0/lib/node_modules/webdriver-manager/selenium/chromedriver_115.0.5790.170.zip
[14:49:41] I/update - chromedriver: unzipping chromedriver_115.0.5790.170.zip
/home/kwisatz/.nvm/versions/node/v18.16.0/lib/node_modules/webdriver-manager/built/lib/cmds/update.js:232
            throw new Error(`Invalid filename: ${path.resolve(outputDir, fileName)}`);
                  ^

Error: Invalid filename: /home/kwisatz/.nvm/versions/node/v18.16.0/lib/node_modules/webdriver-manager/selenium/chromedriver_115.0.5790.170.zip
    at unzip (/home/kwisatz/.nvm/versions/node/v18.16.0/lib/node_modules/webdriver-manager/built/lib/cmds/update.js:232:19)
    at /home/kwisatz/.nvm/versions/node/v18.16.0/lib/node_modules/webdriver-manager/built/lib/cmds/update.js:205:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
```

**Comment by thw0rted** [comment]
I believe that this project, like Protractor, has reached end-of-life.  They haven't gone through and closed out old issues (or updated the README...) but Google has dropped support for the framework.
