### ISSUE TITLE
webdriver-manager update fails on Node 18

### ISSUE THREAD

**Issue by rbirkgit** [angular/webdriver-manager#516]
On  mac/linux when running `webdriver-manager update` it regularly fails on Node 18. Sometimes it works if running it multiple times. It doesn't help to run clean beforehand. Here is an example of the error:

```
[15:19:16] I/config_source - curl -o/home/rbirk/git/consumer-ui/node_modules/webdriver-manager/selenium/standalone-response.xml https://selenium-release.storage.googleapis.com/
[15:19:16] I/config_source - curl -o/home/rbirk/git/consumer-ui/node_modules/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
[15:19:16] I/config_source - curl -o/home/rbirk/git/consumer-ui/node_modules/webdriver-manager/selenium/gecko-response.json https://api.github.com/repos/mozilla/geckodriver/releases
[15:19:16] I/downloader - curl -o/home/rbirk/git/consumer-ui/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
[15:19:16] E/downloader - connect EHOSTUNREACH 198.97.190.53:443
[15:19:16] I/update - chromedriver: file exists /home/rbirk/git/consumer-ui/node_modules/webdriver-manager/selenium/chromedriver_107.0.5304.62.zip
[15:19:16] I/update - chromedriver: unzipping chromedriver_107.0.5304.62.zip
/home/rbirk/git/consumer-ui/node_modules/webdriver-manager/built/lib/cmds/update.js:232
            throw new Error(`Invalid filename: ${path.resolve(outputDir, fileName)}`);
                  ^

Error: Invalid filename: /home/rbirk/git/consumer-ui/node_modules/webdriver-manager/selenium/chromedriver_107.0.5304.62.zip
    at unzip (/home/rbirk/git/consumer-ui/node_modules/webdriver-manager/built/lib/cmds/update.js:232:19)
    at /home/rbirk/git/consumer-ui/node_modules/webdriver-manager/built/lib/cmds/update.js:205:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
```

**Comment by rbirkgit** [comment]
Looks like I get the same error on Node 16 as well. With Node 14 it works fine.
