### ISSUE TITLE
Unhandled 'error' event on webdriver-manager update

### ISSUE THREAD

**Issue by nickwerline** [angular/webdriver-manager#62]
I am trying to upgrade to Protractor 4 and I encountered some errors when updating webdriver-manager. If it matters, I am behind a corporate proxy, but the proxy option has worked fine for webdriver-manager before the Protractor 4 release. 

'protractor --version' gives Version 4.0.0.

'webdriver-manager update ' gives the following error with or without the proxy option:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 74.125.21.128:443
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
```
This error is sometimes preceded by the following, but only always.
```
[15:07:47] I/downloader - selenium standalone: downloading version 2.53.1
[15:07:47] I/downloader - curl -o C:\Program Files\nodejs\node_modules\protractor\node_modules\webdriver-manager\selenium/selenium-server-standalone-2.53.1.jar https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-
2.53.1.jar
``` 

The following error occurs when running 'webdriver-manager start' with or without the proxy option.
```
[14:51:52] I/start - java -jar C:\Program Files\nodejs\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-2.53.1.jar -Dwebdriver.chrome.driver=C:\Program Files\nodejs\node_modules\protractor\node_modu
les\webdriver-manager\selenium\chromedriver_2.22.exe -Dwebdriver.ie.driver=C:\Program Files\nodejs\node_modules\protractor\node_modules\webdriver-manager\selenium\IEDriverServer_x64_2.53.1.exe -Dwebdriver.edge.driver=C:\Program Files (x86)\
Microsoft Web Driver\MicrosoftWebDriver.exe
[14:51:52] I/start - seleniumProcess.pid: 32800
Error: Invalid or corrupt jarfile C:\Program Files\nodejs\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-2.53.1.jar
[14:51:52] I/start - Selenium Standalone has exited with code 1
```

**Comment by nickwerline** [comment]
It seems to still encounter the same error after cleaning.

### With proxy 

```
C:\Users\nwerline>webdriver-manager clean
[14:09:01] I/file_manager - removed chromedriver_2.22.exe
[14:09:01] I/file_manager - removed chromedriver_2.22win32.zip
[14:09:01] I/file_manager - removed IEDriverServer_Win32_2.53.1.exe
[14:09:01] I/file_manager - removed IEDriverServer_Win32_2.53.1.zip
[14:09:01] I/file_manager - removed selenium-server-standalone-2.53.1.jar
```
```
C:\Users\nwerline>webdriver-manager update --ie32 --proxy (the_company_proxy_site)
[14:09:31] I/downloader - selenium standalone: downloading version 2.53.1
[14:09:31] I/downloader - curl -o C:\Program Files\nodejs\node_modules\protractor\node_modules\webdriver-manager\selenium/selenium-server-standalone-2.53.1.jar https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-
2.53.1.jar
[14:09:31] I/downloader - chromedriver: downloading version 2.22
[14:09:31] I/downloader - curl -o C:\Program Files\nodejs\node_modules\protractor\node_modules\webdriver-manager\selenium/chromedriver_2.22win32.zip https://chromedriver.storage.googleapis.com/2.22/chromedriver_win32.zip
[14:09:31] I/downloader - IEDriverServer: downloading version _Win32_2.53.1
[14:09:31] I/downloader - curl -o C:\Program Files\nodejs\node_modules\protractor\node_modules\webdriver-manager\selenium/IEDriverServer_Win32_2.53.1.zip https://selenium-release.storage.googleapis.com/2.53/IEDriverServer_Win32_2.53.1.zip
[14:09:31] I/update - IEDriverServer: unzipping C:\Program Files\nodejs\node_modules\protractor\node_modules\webdriver-manager\selenium\IEDriverServer_Win32_2.53.1.zip
[14:09:32] I/update - chromedriver: unzipping C:\Program Files\nodejs\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.22win32.zip
[14:09:52] E/downloader - Error: Got error Error: connect ETIMEDOUT 74.125.21.128:443 from https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
```

### Without proxy

```
C:\Users\nwerline>webdriver-manager clean
[14:15:49] I/file_manager - removed chromedriver_2.22.exe
[14:15:49] I/file_manager - removed chromedriver_2.22win32.zip
[14:15:49] I/file_manager - removed IEDriverServer_Win32_2.53.1.exe
[14:15:49] I/file_manager - removed IEDriverServer_Win32_2.53.1.zip
```
```
C:\Users\nwerline>webdriver-manager update --ie32
[14:15:58] I/downloader - selenium standalone: downloading version 2.53.1
[14:15:58] I/downloader - curl -o C:\Program Files\nodejs\node_modules\protractor\node_modules\webdriver-manager\selenium/selenium-server-standalone-2.53.1.jar https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-
2.53.1.jar
[14:15:58] I/downloader - chromedriver: downloading version 2.22
[14:15:58] I/downloader - curl -o C:\Program Files\nodejs\node_modules\protractor\node_modules\webdriver-manager\selenium/chromedriver_2.22win32.zip https://chromedriver.storage.googleapis.com/2.22/chromedriver_win32.zip
[14:15:58] I/downloader - IEDriverServer: downloading version _Win32_2.53.1
[14:15:58] I/downloader - curl -o C:\Program Files\nodejs\node_modules\protractor\node_modules\webdriver-manager\selenium/IEDriverServer_Win32_2.53.1.zip https://selenium-release.storage.googleapis.com/2.53/IEDriverServer_Win32_2.53.1.zip
[14:16:19] E/downloader - Error: Got error Error: connect ETIMEDOUT 74.125.21.128:443 from https://chromedriver.storage.googleapis.com/2.22/chromedriver_win32.zip
[14:16:19] E/downloader - Error: Got error Error: connect ETIMEDOUT 74.125.21.128:443 from https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
[14:16:19] E/downloader - Error: Got error Error: connect ETIMEDOUT 74.125.21.128:443 from https://selenium-release.storage.googleapis.com/2.53/IEDriverServer_Win32_2.53.1.zip
```

The chrome driver and ie32 driver seem to be downloading properly, but the standalone is still giving the error.

**Comment by alex87** [comment]
I'm having the same issue, also behind a corporate proxy which was working fine before trying to upgrade to protractor 4.

**Comment by nickwerline** [comment]
@alex87 if it is because of the standalone .jar, you can download it manually and place it in the proper folder. 

https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar

goes to where your other driver folders are, for example:

C:\Program Files\nodejs\node_modules\protractor\node_modules\webdriver-manager\selenium

**Comment by cnishina** [comment]
After reading up on `request`, plan to hopefully resolve this by increasing the timeout to 4 minutes. Timeouts are set default between 20 - 120 seconds per [request](https://github.com/request/request) readme. http://www.sekuda.com/overriding_the_default_linux_kernel_20_second_tcp_socket_connect_timeout
