### ISSUE TITLE
Unable to download chromedriver 2.24

### ISSUE THREAD

**Issue by willsoto-FD** [angular/webdriver-manager#93]
When attempting to update, I get the following output:

```sh
./node_modules/.bin/webdriver-manager update --versions.chrome=2.24                                      
[08:31:32] I/file_manager - creating folder /path/to/node_modules/protractor/node_modules/webdriver-manager/selenium
[08:31:32] I/downloader - selenium standalone: downloading version 2.53.1
[08:31:32] I/downloader - curl -o /path/to/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
[08:31:32] I/downloader - chromedriver: downloading version 2.24
[08:31:32] I/downloader - curl -o /path/to/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.24mac32.zip https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip
[08:31:33] E/downloader - Error: Got code 404 from https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip
[08:31:33] E/downloader - Error: Got error Error: ENOENT: no such file or directory, stat '/path/to/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.24mac32.zip' from https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip
```

I am not certain, but this might be due to the fact that `mac32` is missing from [the download page](http://chromedriver.storage.googleapis.com/index.html?path=2.24/). I guess it has been replaced with mac64?

edit: it looks like this is also the case for [2.23](http://chromedriver.storage.googleapis.com/index.html?path=2.23/)

**Comment by cexbrayat** [comment]
Can we hope for a release containing this fix soon?

As Chrome 54 is now available as stable, Chrome Driver 2.24 looks like the only answer for the Protractor issues (like https://bugs.chromium.org/p/chromedriver/issues/detail?id=1464#c2) that everybody is going to encounter now and sadly we can't use the 2.24 version on MacOS until this fix is released (thx @willsoto-FD by the way).

**Comment by attila123** [comment]
Please,please  somebody fix this issue!
I have webdriver-manager globally installed (npm -g install webdriver-manager).

After I do:
webdriver-manager clean
webdriver-manager update --versions.chrome=2.24

It looks good:

webdriver-manager status
webdriver-manager: using global installed version 10.2.3
[15:48:40] I/status - selenium standalone version available: 2.53.1 [default]
[15:48:40] I/status - chromedriver version available: 2.24
[15:48:40] I/status - android-sdk is not present
[15:48:40] I/status - appium is not present

But when I start it, it wants to load the 2.22 chrome driver somehow (and even '--versions.chome 2.24' does not seem to work with 'start'):

webdriver-manager start
webdriver-manager: using global installed version 10.2.3
[15:50:42] I/start - java -jar /home/avangel/.nvm/versions/node/v4.4.7/lib/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar -Djava.security.egd=file:///dev/./urandom -Dwebdriver.chrome.driver=/home/avangel/.nvm/versions/node/v4.4.7/lib/node_modules/webdriver-manager/selenium/chromedriver_2.22
[15:50:42] I/start - seleniumProcess.pid: 14590
15:50:42.425 INFO - Launching a standalone Selenium Server
Setting system property java.security.egd to file:///dev/./urandom
Setting system property webdriver.chrome.driver to /home/avangel/.nvm/versions/node/v4.4.7/lib/node_modules/webdriver-manager/selenium/chromedriver_2.22

I'm on Linux / 64 bit - if that matters.

**Comment by bhosie** [comment]
also seeing issues this morning with Chrome 54. and `webdriver-manager update` 404's on trying to download 2.24

```
node_modules/.bin/webdriver-manager update --standalone true --versions.chrome 2.24
selenium standalone is up to date.
Updating chromedriver to version 2.24
downloading https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip...
Error: Got code 404 from https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip
Error: Got error Error: ENOENT: no such file or directory, stat '/Users/bhosie/dev/lender-portal/node_modules/protractor/selenium/chromedriver_2.24mac32.zip' from https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip
```

.............

```
[10:44:23] I/launcher - Running 1 instances of WebDriver
[10:44:24] I/testLogger -

[10:44:24] I/testLogger - [chrome #01-0] PID: 19600
[chrome #01-0] Specs: /Users/bhosie/dev/lender-portal/tests/e2e/protractor/assignRep.spec.js
[chrome #01-0]
[chrome #01-0] [10:44:23] I/direct - Using ChromeDriver directly...
[chrome #01-0]
[chrome #01-0] /Users/bhosie/dev/lender-portal/node_modules/selenium-webdriver/error.js:27
[chrome #01-0]     super(opt_error);
[chrome #01-0]          ^
[chrome #01-0] SessionNotCreatedError: session not created exception
[chrome #01-0] from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"19609.1","isDefault":true},"id":1,"name":"","origin":"://"}
[chrome #01-0]   (Session info: chrome=54.0.2840.59)
[chrome #01-0]   (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.6 x86_64)
[chrome #01-0]     at WebDriverError (/Users/bhosie/dev/lender-portal/node_modules/selenium-webdriver/error.js:27:10)
[chrome #01-0]     at SessionNotCreatedError (/Users/bhosie/dev/lender-portal/node_modules/selenium-webdriver/error.js:296:10)
[chrome #01-0]     at Object.checkLegacyResponse (/Users/bhosie/dev/lender-portal/node_modules/selenium-webdriver/error.js:580:13)
[chrome #01-0]     at /Users/bhosie/dev/lender-portal/node_modules/selenium-webdriver/lib/webdriver.js:64:13
[chrome #01-0]     at Promise.invokeCallback_ (/Users/bhosie/dev/lender-portal/node_modules/selenium-webdriver/lib/promise.js:1329:14)
[chrome #01-0]     at TaskQueue.execute_ (/Users/bhosie/dev/lender-portal/node_modules/selenium-webdriver/lib/promise.js:2790:14)
[chrome #01-0]     at TaskQueue.executeNext_ (/Users/bhosie/dev/lender-portal/node_modules/selenium-webdriver/lib/promise.js:2773:21)
[chrome #01-0]     at /Users/bhosie/dev/lender-portal/node_modules/selenium-webdriver/lib/promise.js:2652:27
[chrome #01-0]     at /Users/bhosie/dev/lender-portal/node_modules/selenium-webdriver/lib/promise.js:639:7
[chrome #01-0]     at process._tickCallback (node.js:366:9)
[chrome #01-0] From: Task: WebDriver.createSession()
[chrome #01-0]     at acquireSession (/Users/bhosie/dev/lender-portal/node_modules/selenium-webdriver/lib/webdriver.js:62:22)
[chrome #01-0]     at Function.createSession (/Users/bhosie/dev/lender-portal/node_modules/selenium-webdriver/lib/webdriver.js:295:12)
[chrome #01-0]     at Driver (/Users/bhosie/dev/lender-portal/node_modules/selenium-webdriver/chrome.js:778:38)
[chrome #01-0]     at Direct.getNewDriver (/Users/bhosie/dev/lender-portal/node_modules/protractor/built/driverProviders/direct.js:65:26)
[chrome #01-0]     at Runner.createBrowser (/Users/bhosie/dev/lender-portal/node_modules/protractor/built/runner.js:182:43)
[chrome #01-0]     at /Users/bhosie/dev/lender-portal/node_modules/protractor/built/runner.js:255:30
[chrome #01-0]     at _fulfilled (/Users/bhosie/dev/lender-portal/node_modules/q/q.js:834:54)
[chrome #01-0]     at self.promiseDispatch.done (/Users/bhosie/dev/lender-portal/node_modules/q/q.js:863:30)
[chrome #01-0]     at Promise.promise.promiseDispatch (/Users/bhosie/dev/lender-portal/node_modules/q/q.js:796:13)
[chrome #01-0]     at /Users/bhosie/dev/lender-portal/node_modules/q/q.js:556:49
```

**Comment by shavo007** [comment]
+1

i have this issue too!!
